package auth

import (
	"context"
	"encoding/base64"
	"errors"
	"log/slog"
	"time"
	"uuid"

	"github.com/deepfurry/gofurry-platform/server/internal/database"
	"github.com/deepfurry/gofurry-platform/server/internal/database/sqlc"
	"github.com/gofurry/easyhash"
	"github.com/jackc/pgx/v5"
)

type ChallengeMailer interface {
	SendEmailVerification(context.Context, string, string) error
	SendPasswordReset(context.Context, string, string) error
}

type challengePurpose string

const (
	purposeVerify        challengePurpose = "email_verify"
	purposeReset         challengePurpose = "password_reset"
	VerificationLifetime                  = 24 * time.Hour
	ResetLifetime                         = 30 * time.Minute
	ChallengeCooldown                     = time.Minute
)

type pendingChallenge struct {
	recipient, token string
	purpose          challengePurpose
}

func challengeHash(token string) (string, error) {
	// Only accept the canonical encoding generated by the selected easyhash API.
	if len(token) != 43 {
		return "", ErrChallengeInvalid
	}
	raw, err := base64.RawURLEncoding.Strict().DecodeString(token)
	if err != nil || len(raw) != 32 {
		return "", ErrChallengeInvalid
	}
	hash, err := easyhash.HashToken(token)
	if err != nil {
		return "", ErrChallengeInvalid
	}
	return hash, nil
}

// Call inside the registration transaction, or while holding the user's
// User auth lock. The partial unique index is the final issuance invariant.
func issueChallenge(ctx context.Context, q *sqlc.Queries, userID, identityID uuid.UUID, email string, purpose challengePurpose, now time.Time) (*pendingChallenge, error) {
	latest, err := q.GetLatestChallenge(ctx, sqlc.GetLatestChallengeParams{AuthIdentityID: dbID(identityID), Purpose: string(purpose)})
	if err == nil && latest.CreatedAt.Time.Add(ChallengeCooldown).After(now) {
		return nil, nil
	}
	if err != nil && !errors.Is(err, pgx.ErrNoRows) {
		return nil, database.SafeError("check challenge cooldown", err)
	}
	token, err := easyhash.GenerateToken()
	if err != nil {
		return nil, ErrMailUnavailable
	}
	hash, err := challengeHash(token)
	if err != nil {
		return nil, ErrMailUnavailable
	}
	if err = invalidateChallenges(ctx, q, userID, purpose, now); err != nil {
		return nil, err
	}
	lifetime := VerificationLifetime
	if purpose == purposeReset {
		lifetime = ResetLifetime
	}
	err = q.CreateAuthChallenge(ctx, sqlc.CreateAuthChallengeParams{ID: dbID(uuid.NewV7()), UserID: dbID(userID), AuthIdentityID: dbID(identityID),
		Purpose: string(purpose), TokenHash: hash, CreatedAt: timestamp(now), ExpiresAt: timestamp(now.Add(lifetime))})
	if err != nil {
		return nil, database.SafeError("create challenge", err)
	}
	event := verificationRequested
	if purpose == purposeReset {
		event = resetRequested
	}
	if err = recordEvent(ctx, q, event, userID, uuid.Nil(), now); err != nil {
		return nil, err
	}
	return &pendingChallenge{recipient: email, token: token, purpose: purpose}, nil
}

func invalidateChallenges(ctx context.Context, q *sqlc.Queries, userID uuid.UUID, purpose challengePurpose, now time.Time) error {
	err := q.InvalidateActiveChallenges(ctx, sqlc.InvalidateActiveChallengesParams{UserID: dbID(userID), Purpose: string(purpose), Now: timestamp(now)})
	if err != nil {
		return database.SafeError("invalidate challenges", err)
	}
	return nil
}

// Deliver only after commit, with a bounded context independent of a disconnected
// HTTP request. No raw sender error or message data is logged or returned.
func (a *App) deliver(ctx context.Context, pending *pendingChallenge) error {
	if pending == nil {
		return nil
	}
	deliveryCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), 2*time.Second)
	defer cancel()
	var err error
	if pending.purpose == purposeVerify {
		err = a.mailer.SendEmailVerification(deliveryCtx, pending.recipient, pending.token)
	} else {
		err = a.mailer.SendPasswordReset(deliveryCtx, pending.recipient, pending.token)
	}
	if err != nil {
		return ErrMailUnavailable
	}
	return nil
}

func (a *App) RequestVerification(ctx context.Context, actor Actor) error {
	tx, err := a.pool.Begin(ctx)
	if err != nil {
		return database.SafeError("begin verification request", err)
	}
	defer tx.Rollback(ctx)
	q := sqlc.New(tx)
	if err = lockUser(ctx, q, actor.UserID); err != nil {
		return err
	}
	now := a.now().UTC()
	if err = requireActor(ctx, q, actor, now); err != nil {
		return err
	}
	identity, err := q.GetLocalEmailIdentityForUser(ctx, dbID(actor.UserID))
	if errors.Is(err, pgx.ErrNoRows) {
		return ErrUnauthenticated
	}
	if err != nil {
		return database.SafeError("read verification identity", err)
	}
	if identity.VerifiedAt.Valid {
		return nil
	}
	pending, err := issueChallenge(ctx, q, actor.UserID, uuid.UUID(identity.ID.Bytes), identity.Email.String, purposeVerify, now)
	if err != nil {
		return err
	}
	if err = tx.Commit(ctx); err != nil {
		return database.SafeError("commit verification request", err)
	}
	return a.deliver(ctx, pending)
}

func (a *App) RequestPasswordReset(ctx context.Context, email string) {
	normalized, err := NormalizeEmail(email)
	if err != nil {
		return
	}
	if _, err = a.throttleCheck(ctx, PasswordResetLimit, normalized, true); err != nil {
		return
	}
	// Eligible and unknown accounts share the same bounded KDF. A limited
	// subject skips expensive work without disclosing account existence.
	_, _, _, _ = verifyPassword(newToken(), a.dummyHash)
	if err = a.requestReset(ctx, normalized); err != nil {
		slog.Warn("password reset request could not be completed", "component", "auth")
	}
	// All eligible, ineligible and delivery-failure paths have the same public
	// response. Operational errors contain no address, token or driver details.
}

func (a *App) requestReset(ctx context.Context, email string) error {
	row, err := sqlc.New(a.pool).FindLocalCredentialByEmailSubject(ctx, email)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil
	}
	if err != nil {
		return database.SafeError("lookup reset eligibility", err)
	}
	if row.AccountState != "active" || row.DeletedAt.Valid {
		return nil
	}
	tx, err := a.pool.Begin(ctx)
	if err != nil {
		return database.SafeError("begin reset request", err)
	}
	defer tx.Rollback(ctx)
	q, userID := sqlc.New(tx), uuid.UUID(row.ID.Bytes)
	if _, err = lockCredential(ctx, q, userID); errors.Is(err, ErrUnauthenticated) {
		return nil
	}
	if err != nil {
		return err
	}
	identity, err := q.GetLocalEmailIdentityForUser(ctx, row.ID)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil
	}
	if err != nil {
		return database.SafeError("read reset identity", err)
	}
	pending, err := issueChallenge(ctx, q, userID, uuid.UUID(identity.ID.Bytes), identity.Email.String, purposeReset, a.now().UTC())
	if err != nil {
		return err
	}
	if err = tx.Commit(ctx); err != nil {
		return database.SafeError("commit reset request", err)
	}
	return a.deliver(ctx, pending)
}

func (a *App) initialChallenge(ctx context.Context, token string, purpose challengePurpose) (sqlc.FindActiveChallengeByTokenHashRow, error) {
	hash, err := challengeHash(token)
	if err != nil {
		return sqlc.FindActiveChallengeByTokenHashRow{}, err
	}
	row, err := sqlc.New(a.pool).FindActiveChallengeByTokenHash(ctx, sqlc.FindActiveChallengeByTokenHashParams{TokenHash: hash, Purpose: string(purpose), Now: timestamp(a.now().UTC())})
	if errors.Is(err, pgx.ErrNoRows) {
		return row, ErrChallengeInvalid
	}
	if err != nil {
		return row, database.SafeError("find challenge", err)
	}
	return row, nil
}

func lockChallenge(ctx context.Context, q *sqlc.Queries, token string, purpose challengePurpose, now time.Time) (sqlc.FindActiveChallengeByTokenHashForUpdateRow, error) {
	hash, err := challengeHash(token)
	if err != nil {
		return sqlc.FindActiveChallengeByTokenHashForUpdateRow{}, err
	}
	row, err := q.FindActiveChallengeByTokenHashForUpdate(ctx, sqlc.FindActiveChallengeByTokenHashForUpdateParams{TokenHash: hash, Purpose: string(purpose), Now: timestamp(now)})
	if errors.Is(err, pgx.ErrNoRows) {
		return row, ErrChallengeInvalid
	}
	if err != nil {
		return row, database.SafeError("lock challenge", err)
	}
	if ok, err := easyhash.VerifyToken(token, row.TokenHash); err != nil || !ok {
		return row, ErrChallengeInvalid
	}
	return row, nil
}

func consumeChallenge(ctx context.Context, q *sqlc.Queries, id, userID uuid.UUID, purpose challengePurpose, now time.Time) error {
	count, err := q.ConsumeChallenge(ctx, sqlc.ConsumeChallengeParams{ID: dbID(id), Now: timestamp(now)})
	if err != nil {
		return database.SafeError("consume challenge", err)
	}
	if count != 1 {
		return ErrChallengeInvalid
	}
	return invalidateChallenges(ctx, q, userID, purpose, now)
}

func (a *App) VerifyEmail(ctx context.Context, token string) error {
	initial, err := a.initialChallenge(ctx, token, purposeVerify)
	if err != nil {
		return err
	}
	tx, err := a.pool.Begin(ctx)
	if err != nil {
		return database.SafeError("begin email verification", err)
	}
	defer tx.Rollback(ctx)
	q, userID := sqlc.New(tx), uuid.UUID(initial.UserID.Bytes)
	if err = lockUser(ctx, q, userID); errors.Is(err, ErrUnauthenticated) {
		return ErrChallengeInvalid
	}
	if err != nil {
		return err
	}
	now := a.now().UTC()
	challenge, err := lockChallenge(ctx, q, token, purposeVerify, now)
	if err != nil {
		return err
	}
	count, err := q.MarkEmailIdentityVerified(ctx, sqlc.MarkEmailIdentityVerifiedParams{ID: challenge.AuthIdentityID, UserID: challenge.UserID, Now: timestamp(now)})
	if err != nil {
		return database.SafeError("verify email identity", err)
	}
	if count != 1 {
		return ErrChallengeInvalid
	}
	if err = consumeChallenge(ctx, q, uuid.UUID(challenge.ID.Bytes), userID, purposeVerify, now); err != nil {
		return err
	}
	if err = recordEvent(ctx, q, emailVerified, userID, uuid.Nil(), now); err != nil {
		return err
	}
	if err = tx.Commit(ctx); err != nil {
		return database.SafeError("commit email verification", err)
	}
	return nil
}
