// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_resource.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCategoryLocalizations = `-- name: AdminCategoryLocalizations :many
SELECT category_id, locale, name, description, created_at, updated_at FROM app.category_localizations WHERE category_id=$1 ORDER BY locale
`

func (q *Queries) AdminCategoryLocalizations(ctx context.Context, categoryID pgtype.UUID) ([]AppCategoryLocalization, error) {
	rows, err := q.db.Query(ctx, adminCategoryLocalizations, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppCategoryLocalization{}
	for rows.Next() {
		var i AppCategoryLocalization
		if err := rows.Scan(
			&i.CategoryID,
			&i.Locale,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminResourceExternalIDs = `-- name: AdminResourceExternalIDs :many
SELECT resource_id, namespace, external_id, created_at FROM app.resource_external_ids WHERE resource_id=$1 ORDER BY namespace,external_id
`

func (q *Queries) AdminResourceExternalIDs(ctx context.Context, resourceID pgtype.UUID) ([]AppResourceExternalID, error) {
	rows, err := q.db.Query(ctx, adminResourceExternalIDs, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppResourceExternalID{}
	for rows.Next() {
		var i AppResourceExternalID
		if err := rows.Scan(
			&i.ResourceID,
			&i.Namespace,
			&i.ExternalID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminResourceLocalizations = `-- name: AdminResourceLocalizations :many
SELECT resource_id, locale, name, summary, description, created_at, updated_at FROM app.resource_localizations WHERE resource_id=$1 ORDER BY locale
`

func (q *Queries) AdminResourceLocalizations(ctx context.Context, resourceID pgtype.UUID) ([]AppResourceLocalization, error) {
	rows, err := q.db.Query(ctx, adminResourceLocalizations, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppResourceLocalization{}
	for rows.Next() {
		var i AppResourceLocalization
		if err := rows.Scan(
			&i.ResourceID,
			&i.Locale,
			&i.Name,
			&i.Summary,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminResourceRelations = `-- name: AdminResourceRelations :many
SELECT rr.id, rr.source_resource_id, rr.target_resource_id, rr.relation_type, rr.created_at, r.id AS other_id,r.slug AS other_slug,l.name AS other_name,r.publication_state AS other_publication_state,
 CASE WHEN rr.relation_type='related_to' THEN 'symmetric' WHEN rr.source_resource_id=$1 THEN 'outgoing' ELSE 'incoming' END::text AS direction
FROM app.resource_relations rr
JOIN app.resources r ON r.id=CASE WHEN rr.source_resource_id=$1 THEN rr.target_resource_id ELSE rr.source_resource_id END
LEFT JOIN app.resource_localizations l ON l.resource_id=r.id AND l.locale=r.default_locale
WHERE (rr.source_resource_id=$1 OR rr.target_resource_id=$1) AND r.deleted_at IS NULL
ORDER BY rr.relation_type,rr.id
`

type AdminResourceRelationsRow struct {
	ID                    pgtype.UUID
	SourceResourceID      pgtype.UUID
	TargetResourceID      pgtype.UUID
	RelationType          string
	CreatedAt             pgtype.Timestamptz
	OtherID               pgtype.UUID
	OtherSlug             string
	OtherName             pgtype.Text
	OtherPublicationState string
	Direction             string
}

func (q *Queries) AdminResourceRelations(ctx context.Context, anchorID pgtype.UUID) ([]AdminResourceRelationsRow, error) {
	rows, err := q.db.Query(ctx, adminResourceRelations, anchorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminResourceRelationsRow{}
	for rows.Next() {
		var i AdminResourceRelationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceResourceID,
			&i.TargetResourceID,
			&i.RelationType,
			&i.CreatedAt,
			&i.OtherID,
			&i.OtherSlug,
			&i.OtherName,
			&i.OtherPublicationState,
			&i.Direction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminResourceSources = `-- name: AdminResourceSources :many
SELECT id, resource_id, url, label, source_type, availability_state, rights_status, is_primary, created_at, updated_at FROM app.resource_sources WHERE resource_id=$1 ORDER BY created_at,id
`

func (q *Queries) AdminResourceSources(ctx context.Context, resourceID pgtype.UUID) ([]AppResourceSource, error) {
	rows, err := q.db.Query(ctx, adminResourceSources, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppResourceSource{}
	for rows.Next() {
		var i AppResourceSource
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Url,
			&i.Label,
			&i.SourceType,
			&i.AvailabilityState,
			&i.RightsStatus,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminResourceTags = `-- name: AdminResourceTags :many
SELECT t.id, t.slug, t.default_locale, t.state, t.created_at, t.updated_at, t.deleted_at, l.name FROM app.tags t JOIN app.resource_tags rt ON rt.tag_id=t.id
LEFT JOIN app.tag_localizations l ON l.tag_id=t.id AND l.locale=t.default_locale
WHERE rt.resource_id=$1 ORDER BY t.slug,t.id
`

type AdminResourceTagsRow struct {
	ID            pgtype.UUID
	Slug          string
	DefaultLocale string
	State         string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	Name          pgtype.Text
}

func (q *Queries) AdminResourceTags(ctx context.Context, resourceID pgtype.UUID) ([]AdminResourceTagsRow, error) {
	rows, err := q.db.Query(ctx, adminResourceTags, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminResourceTagsRow{}
	for rows.Next() {
		var i AdminResourceTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DefaultLocale,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminTagLocalizations = `-- name: AdminTagLocalizations :many
SELECT tag_id, locale, name, description, created_at, updated_at FROM app.tag_localizations WHERE tag_id=$1 ORDER BY locale
`

func (q *Queries) AdminTagLocalizations(ctx context.Context, tagID pgtype.UUID) ([]AppTagLocalization, error) {
	rows, err := q.db.Query(ctx, adminTagLocalizations, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppTagLocalization{}
	for rows.Next() {
		var i AppTagLocalization
		if err := rows.Scan(
			&i.TagID,
			&i.Locale,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminCategory = `-- name: GetAdminCategory :one
SELECT id, slug, default_locale, state, created_at, updated_at, deleted_at FROM app.categories WHERE id=$1 AND deleted_at IS NULL
`

func (q *Queries) GetAdminCategory(ctx context.Context, id pgtype.UUID) (AppCategory, error) {
	row := q.db.QueryRow(ctx, getAdminCategory, id)
	var i AppCategory
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DefaultLocale,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAdminResource = `-- name: GetAdminResource :one
SELECT r.id, r.slug, r.default_locale, r.category_id, r.publication_state, r.lifecycle, r.content_rating, r.version, r.published_at, r.created_at, r.updated_at, r.deleted_at, c.slug AS category_slug, c.default_locale AS category_locale,
       c.state AS category_state, cl.name AS category_name
FROM app.resources r JOIN app.categories c ON c.id=r.category_id
LEFT JOIN app.category_localizations cl ON cl.category_id=c.id AND cl.locale=c.default_locale
WHERE r.id=$1 AND r.deleted_at IS NULL
`

type GetAdminResourceRow struct {
	ID               pgtype.UUID
	Slug             string
	DefaultLocale    string
	CategoryID       pgtype.UUID
	PublicationState string
	Lifecycle        string
	ContentRating    string
	Version          int64
	PublishedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	CategorySlug     string
	CategoryLocale   string
	CategoryState    string
	CategoryName     pgtype.Text
}

func (q *Queries) GetAdminResource(ctx context.Context, id pgtype.UUID) (GetAdminResourceRow, error) {
	row := q.db.QueryRow(ctx, getAdminResource, id)
	var i GetAdminResourceRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DefaultLocale,
		&i.CategoryID,
		&i.PublicationState,
		&i.Lifecycle,
		&i.ContentRating,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CategorySlug,
		&i.CategoryLocale,
		&i.CategoryState,
		&i.CategoryName,
	)
	return i, err
}

const getAdminTag = `-- name: GetAdminTag :one
SELECT id, slug, default_locale, state, created_at, updated_at, deleted_at FROM app.tags WHERE id=$1 AND deleted_at IS NULL
`

func (q *Queries) GetAdminTag(ctx context.Context, id pgtype.UUID) (AppTag, error) {
	row := q.db.QueryRow(ctx, getAdminTag, id)
	var i AppTag
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DefaultLocale,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAdminCategories = `-- name: ListAdminCategories :many
SELECT t.id, t.slug, t.default_locale, t.state, t.created_at, t.updated_at, t.deleted_at,l.name FROM app.categories t LEFT JOIN app.category_localizations l ON l.category_id=t.id AND l.locale=t.default_locale
WHERE t.deleted_at IS NULL ORDER BY t.slug,t.id
`

type ListAdminCategoriesRow struct {
	ID            pgtype.UUID
	Slug          string
	DefaultLocale string
	State         string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	Name          pgtype.Text
}

func (q *Queries) ListAdminCategories(ctx context.Context) ([]ListAdminCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listAdminCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminCategoriesRow{}
	for rows.Next() {
		var i ListAdminCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DefaultLocale,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminResources = `-- name: ListAdminResources :many
SELECT r.id, r.slug, r.default_locale, r.category_id, r.publication_state, r.lifecycle, r.content_rating, r.version, r.published_at, r.created_at, r.updated_at, r.deleted_at, l.name, c.slug AS category_slug, c.default_locale AS category_locale,
       c.state AS category_state, cl.name AS category_name
FROM app.resources r
LEFT JOIN app.resource_localizations l ON l.resource_id=r.id AND l.locale=r.default_locale
JOIN app.categories c ON c.id=r.category_id
LEFT JOIN app.category_localizations cl ON cl.category_id=c.id AND cl.locale=c.default_locale
WHERE r.deleted_at IS NULL
 AND ($1::text IS NULL OR r.publication_state=$1)
 AND ($2::uuid IS NULL OR r.category_id=$2)
 AND ($3::text IS NULL OR r.slug=$3)
ORDER BY r.updated_at DESC, r.id DESC LIMIT $5::bigint OFFSET $4::bigint
`

type ListAdminResourcesParams struct {
	PublicationState pgtype.Text
	CategoryID       pgtype.UUID
	Slug             pgtype.Text
	RowOffset        int64
	RowLimit         int64
}

type ListAdminResourcesRow struct {
	ID               pgtype.UUID
	Slug             string
	DefaultLocale    string
	CategoryID       pgtype.UUID
	PublicationState string
	Lifecycle        string
	ContentRating    string
	Version          int64
	PublishedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	Name             pgtype.Text
	CategorySlug     string
	CategoryLocale   string
	CategoryState    string
	CategoryName     pgtype.Text
}

func (q *Queries) ListAdminResources(ctx context.Context, arg ListAdminResourcesParams) ([]ListAdminResourcesRow, error) {
	rows, err := q.db.Query(ctx, listAdminResources,
		arg.PublicationState,
		arg.CategoryID,
		arg.Slug,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminResourcesRow{}
	for rows.Next() {
		var i ListAdminResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DefaultLocale,
			&i.CategoryID,
			&i.PublicationState,
			&i.Lifecycle,
			&i.ContentRating,
			&i.Version,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.CategorySlug,
			&i.CategoryLocale,
			&i.CategoryState,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminTags = `-- name: ListAdminTags :many
SELECT t.id, t.slug, t.default_locale, t.state, t.created_at, t.updated_at, t.deleted_at,l.name FROM app.tags t LEFT JOIN app.tag_localizations l ON l.tag_id=t.id AND l.locale=t.default_locale
WHERE t.deleted_at IS NULL ORDER BY t.slug,t.id
`

type ListAdminTagsRow struct {
	ID            pgtype.UUID
	Slug          string
	DefaultLocale string
	State         string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	Name          pgtype.Text
}

func (q *Queries) ListAdminTags(ctx context.Context) ([]ListAdminTagsRow, error) {
	rows, err := q.db.Query(ctx, listAdminTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminTagsRow{}
	for rows.Next() {
		var i ListAdminTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DefaultLocale,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
