// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*) FROM app.user_roles r JOIN app.users u ON u.id = r.user_id
WHERE r.role = 'admin' AND u.account_state = 'active' AND u.deleted_at IS NULL
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminSession = `-- name: CreateAdminSession :exec
INSERT INTO app.sessions (id, user_id, kind, auth_method, token_hash, authenticated_at, created_at,
                          last_seen_at, idle_expires_at, absolute_expires_at)
VALUES ($1, $2, 'admin', 'password', $3, $4, $4, $4, $5, $6)
`

type CreateAdminSessionParams struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	TokenHash         []byte
	Now               pgtype.Timestamptz
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) error {
	_, err := q.db.Exec(ctx, createAdminSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Now,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	return err
}

const findActiveAdminSession = `-- name: FindActiveAdminSession :one
SELECT s.id, s.user_id, s.authenticated_at, s.last_seen_at
FROM app.sessions s JOIN app.users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.kind = 'admin' AND s.auth_method = 'password' AND s.revoked_at IS NULL
  AND s.idle_expires_at > $2 AND s.absolute_expires_at > $2
  AND u.account_state = 'active' AND u.deleted_at IS NULL
`

type FindActiveAdminSessionParams struct {
	TokenHash []byte
	Now       pgtype.Timestamptz
}

type FindActiveAdminSessionRow struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	AuthenticatedAt pgtype.Timestamptz
	LastSeenAt      pgtype.Timestamptz
}

func (q *Queries) FindActiveAdminSession(ctx context.Context, arg FindActiveAdminSessionParams) (FindActiveAdminSessionRow, error) {
	row := q.db.QueryRow(ctx, findActiveAdminSession, arg.TokenHash, arg.Now)
	var i FindActiveAdminSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthenticatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getActiveAdminSessionByID = `-- name: GetActiveAdminSessionByID :one
SELECT s.id, s.authenticated_at FROM app.sessions s JOIN app.users u ON u.id = s.user_id
WHERE s.id = $1 AND s.user_id = $2 AND s.kind = 'admin' AND s.auth_method = 'password'
  AND s.revoked_at IS NULL AND s.idle_expires_at > $3 AND s.absolute_expires_at > $3
  AND u.account_state = 'active' AND u.deleted_at IS NULL
`

type GetActiveAdminSessionByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Now    pgtype.Timestamptz
}

type GetActiveAdminSessionByIDRow struct {
	ID              pgtype.UUID
	AuthenticatedAt pgtype.Timestamptz
}

func (q *Queries) GetActiveAdminSessionByID(ctx context.Context, arg GetActiveAdminSessionByIDParams) (GetActiveAdminSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveAdminSessionByID, arg.ID, arg.UserID, arg.Now)
	var i GetActiveAdminSessionByIDRow
	err := row.Scan(&i.ID, &i.AuthenticatedAt)
	return i, err
}

const grantUserRole = `-- name: GrantUserRole :execrows
INSERT INTO app.user_roles (user_id, role, created_at) VALUES ($1, $2, $3)
ON CONFLICT (user_id, role) DO NOTHING
`

type GrantUserRoleParams struct {
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GrantUserRole(ctx context.Context, arg GrantUserRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, grantUserRole, arg.UserID, arg.Role, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveAdminSessions = `-- name: ListActiveAdminSessions :many
SELECT id, authenticated_at, created_at, last_seen_at, idle_expires_at, absolute_expires_at
FROM app.sessions WHERE user_id = $1 AND kind = 'admin' AND revoked_at IS NULL
  AND idle_expires_at > $2 AND absolute_expires_at > $2
ORDER BY created_at DESC, id DESC
`

type ListActiveAdminSessionsParams struct {
	UserID pgtype.UUID
	Now    pgtype.Timestamptz
}

type ListActiveAdminSessionsRow struct {
	ID                pgtype.UUID
	AuthenticatedAt   pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
}

func (q *Queries) ListActiveAdminSessions(ctx context.Context, arg ListActiveAdminSessionsParams) ([]ListActiveAdminSessionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAdminSessions, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAdminSessionsRow{}
	for rows.Next() {
		var i ListActiveAdminSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthenticatedAt,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.IdleExpiresAt,
			&i.AbsoluteExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT role FROM app.user_roles WHERE user_id = $1 ORDER BY role
`

func (q *Queries) ListUserRoles(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRoleOperations = `-- name: LockRoleOperations :exec
SELECT pg_advisory_xact_lock(72463159018201)
`

func (q *Queries) LockRoleOperations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockRoleOperations)
	return err
}

const lockRoleUserByEmail = `-- name: LockRoleUserByEmail :one
SELECT u.id, u.account_state, u.deleted_at, a.verified_at,
       EXISTS (SELECT 1 FROM app.password_credentials c WHERE c.user_id = u.id) AS has_password
FROM app.users u JOIN app.auth_identities a ON a.user_id = u.id
WHERE a.provider = 'email' AND a.provider_subject = $1
FOR UPDATE OF u
`

type LockRoleUserByEmailRow struct {
	ID           pgtype.UUID
	AccountState string
	DeletedAt    pgtype.Timestamptz
	VerifiedAt   pgtype.Timestamptz
	HasPassword  bool
}

func (q *Queries) LockRoleUserByEmail(ctx context.Context, providerSubject string) (LockRoleUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, lockRoleUserByEmail, providerSubject)
	var i LockRoleUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.AccountState,
		&i.DeletedAt,
		&i.VerifiedAt,
		&i.HasPassword,
	)
	return i, err
}

const readAdminAccount = `-- name: ReadAdminAccount :one
SELECT u.id, a.email FROM app.users u JOIN app.auth_identities a ON a.user_id = u.id
WHERE u.id = $1 AND a.provider = 'email' AND a.email IS NOT NULL AND a.verified_at IS NOT NULL
  AND u.account_state = 'active' AND u.deleted_at IS NULL
  AND EXISTS (SELECT 1 FROM app.password_credentials c WHERE c.user_id = u.id)
`

type ReadAdminAccountRow struct {
	ID    pgtype.UUID
	Email pgtype.Text
}

func (q *Queries) ReadAdminAccount(ctx context.Context, id pgtype.UUID) (ReadAdminAccountRow, error) {
	row := q.db.QueryRow(ctx, readAdminAccount, id)
	var i ReadAdminAccountRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const revokeAdminSessionByID = `-- name: RevokeAdminSessionByID :execrows
UPDATE app.sessions SET revoked_at = $1
WHERE id = $2 AND user_id = $3 AND kind = 'admin' AND revoked_at IS NULL
  AND idle_expires_at > $1 AND absolute_expires_at > $1
`

type RevokeAdminSessionByIDParams struct {
	Now    pgtype.Timestamptz
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RevokeAdminSessionByID(ctx context.Context, arg RevokeAdminSessionByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAdminSessionByID, arg.Now, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllAdminSessions = `-- name: RevokeAllAdminSessions :exec
UPDATE app.sessions SET revoked_at = $1
WHERE user_id = $2 AND kind = 'admin' AND revoked_at IS NULL
`

type RevokeAllAdminSessionsParams struct {
	Now    pgtype.Timestamptz
	UserID pgtype.UUID
}

func (q *Queries) RevokeAllAdminSessions(ctx context.Context, arg RevokeAllAdminSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllAdminSessions, arg.Now, arg.UserID)
	return err
}

const revokeOtherAdminSessions = `-- name: RevokeOtherAdminSessions :exec
UPDATE app.sessions SET revoked_at = $1
WHERE user_id = $2 AND id <> $3 AND kind = 'admin' AND revoked_at IS NULL
`

type RevokeOtherAdminSessionsParams struct {
	Now       pgtype.Timestamptz
	UserID    pgtype.UUID
	CurrentID pgtype.UUID
}

func (q *Queries) RevokeOtherAdminSessions(ctx context.Context, arg RevokeOtherAdminSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherAdminSessions, arg.Now, arg.UserID, arg.CurrentID)
	return err
}

const revokeUserRole = `-- name: RevokeUserRole :execrows
DELETE FROM app.user_roles WHERE user_id = $1 AND role = $2
`

type RevokeUserRoleParams struct {
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) RevokeUserRole(ctx context.Context, arg RevokeUserRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserRole, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAdminSession = `-- name: TouchAdminSession :execrows
UPDATE app.sessions s SET last_seen_at = $1,
    idle_expires_at = LEAST($2::timestamptz, s.absolute_expires_at)
WHERE s.id = $3 AND s.kind = 'admin' AND s.revoked_at IS NULL
  AND s.idle_expires_at > $1 AND s.absolute_expires_at > $1
  AND s.last_seen_at <= $4
  AND EXISTS (SELECT 1 FROM app.users u WHERE u.id = s.user_id AND u.account_state = 'active' AND u.deleted_at IS NULL)
  AND EXISTS (SELECT 1 FROM app.user_roles r WHERE r.user_id = s.user_id)
`

type TouchAdminSessionParams struct {
	Now           pgtype.Timestamptz
	IdleExpiresAt pgtype.Timestamptz
	ID            pgtype.UUID
	TouchBefore   pgtype.Timestamptz
}

func (q *Queries) TouchAdminSession(ctx context.Context, arg TouchAdminSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchAdminSession,
		arg.Now,
		arg.IdleExpiresAt,
		arg.ID,
		arg.TouchBefore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
