// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contribution.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const contributionAdminHistory = `-- name: ContributionAdminHistory :many
SELECT contribution_id, event_type, actor_id, message, internal_note, occurred_at FROM app.contribution_events WHERE contribution_id=$1 ORDER BY occurred_at,event_type
`

func (q *Queries) ContributionAdminHistory(ctx context.Context, contributionID pgtype.UUID) ([]AppContributionEvent, error) {
	rows, err := q.db.Query(ctx, contributionAdminHistory, contributionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppContributionEvent{}
	for rows.Next() {
		var i AppContributionEvent
		if err := rows.Scan(
			&i.ContributionID,
			&i.EventType,
			&i.ActorID,
			&i.Message,
			&i.InternalNote,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contributionAudit = `-- name: ContributionAudit :exec
INSERT INTO app.contribution_review_audits(contribution_id,actor_id,action,resource_id,before_version,after_version,occurred_at)
SELECT id,$2,status,$3,$4,$5,decided_at FROM app.contributions WHERE id=$1
`

type ContributionAuditParams struct {
	ID            pgtype.UUID
	ActorID       pgtype.UUID
	ResourceID    pgtype.UUID
	BeforeVersion pgtype.Int8
	AfterVersion  pgtype.Int8
}

func (q *Queries) ContributionAudit(ctx context.Context, arg ContributionAuditParams) error {
	_, err := q.db.Exec(ctx, contributionAudit,
		arg.ID,
		arg.ActorID,
		arg.ResourceID,
		arg.BeforeVersion,
		arg.AfterVersion,
	)
	return err
}

const contributionByRequest = `-- name: ContributionByRequest :one
SELECT id, author_id, kind, target_resource_id, base_version, status, reason, previous_id, request_id, request_fingerprint, submitted_fields, result_resource_id, result_version, created_at, decided_at FROM app.contributions WHERE author_id=$1 AND request_id=$2
`

type ContributionByRequestParams struct {
	AuthorID  pgtype.UUID
	RequestID pgtype.UUID
}

func (q *Queries) ContributionByRequest(ctx context.Context, arg ContributionByRequestParams) (AppContribution, error) {
	row := q.db.QueryRow(ctx, contributionByRequest, arg.AuthorID, arg.RequestID)
	var i AppContribution
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Kind,
		&i.TargetResourceID,
		&i.BaseVersion,
		&i.Status,
		&i.Reason,
		&i.PreviousID,
		&i.RequestID,
		&i.RequestFingerprint,
		&i.SubmittedFields,
		&i.ResultResourceID,
		&i.ResultVersion,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const contributionCategory = `-- name: ContributionCategory :one
SELECT state FROM app.categories WHERE id=$1 AND deleted_at IS NULL
`

func (q *Queries) ContributionCategory(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, contributionCategory, id)
	var state string
	err := row.Scan(&state)
	return state, err
}

const contributionContents = `-- name: ContributionContents :many
SELECT c.contribution_id, c.content_kind, c.default_locale, c.category_id, c.name, c.summary, c.description, c.lifecycle, c.content_rating, c.slug,s.url,s.label,s.source_type,s.availability_state
FROM app.contribution_contents c LEFT JOIN app.contribution_initial_sources s USING(contribution_id,content_kind)
WHERE c.contribution_id=$1 ORDER BY c.content_kind
`

type ContributionContentsRow struct {
	ContributionID    pgtype.UUID
	ContentKind       string
	DefaultLocale     string
	CategoryID        pgtype.UUID
	Name              string
	Summary           pgtype.Text
	Description       pgtype.Text
	Lifecycle         string
	ContentRating     string
	Slug              pgtype.Text
	Url               pgtype.Text
	Label             pgtype.Text
	SourceType        pgtype.Text
	AvailabilityState pgtype.Text
}

func (q *Queries) ContributionContents(ctx context.Context, contributionID pgtype.UUID) ([]ContributionContentsRow, error) {
	rows, err := q.db.Query(ctx, contributionContents, contributionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContributionContentsRow{}
	for rows.Next() {
		var i ContributionContentsRow
		if err := rows.Scan(
			&i.ContributionID,
			&i.ContentKind,
			&i.DefaultLocale,
			&i.CategoryID,
			&i.Name,
			&i.Summary,
			&i.Description,
			&i.Lifecycle,
			&i.ContentRating,
			&i.Slug,
			&i.Url,
			&i.Label,
			&i.SourceType,
			&i.AvailabilityState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contributionCreate = `-- name: ContributionCreate :one
INSERT INTO app.contributions(id,author_id,kind,target_resource_id,base_version,reason,previous_id,request_id,request_fingerprint,submitted_fields)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id, author_id, kind, target_resource_id, base_version, status, reason, previous_id, request_id, request_fingerprint, submitted_fields, result_resource_id, result_version, created_at, decided_at
`

type ContributionCreateParams struct {
	ID                 pgtype.UUID
	AuthorID           pgtype.UUID
	Kind               string
	TargetResourceID   pgtype.UUID
	BaseVersion        pgtype.Int8
	Reason             string
	PreviousID         pgtype.UUID
	RequestID          pgtype.UUID
	RequestFingerprint []byte
	SubmittedFields    int16
}

func (q *Queries) ContributionCreate(ctx context.Context, arg ContributionCreateParams) (AppContribution, error) {
	row := q.db.QueryRow(ctx, contributionCreate,
		arg.ID,
		arg.AuthorID,
		arg.Kind,
		arg.TargetResourceID,
		arg.BaseVersion,
		arg.Reason,
		arg.PreviousID,
		arg.RequestID,
		arg.RequestFingerprint,
		arg.SubmittedFields,
	)
	var i AppContribution
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Kind,
		&i.TargetResourceID,
		&i.BaseVersion,
		&i.Status,
		&i.Reason,
		&i.PreviousID,
		&i.RequestID,
		&i.RequestFingerprint,
		&i.SubmittedFields,
		&i.ResultResourceID,
		&i.ResultVersion,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const contributionDecide = `-- name: ContributionDecide :one
UPDATE app.contributions SET status=$2,result_resource_id=$3,result_version=$4,decided_at=clock_timestamp()
WHERE id=$1 AND status='pending' RETURNING id, author_id, kind, target_resource_id, base_version, status, reason, previous_id, request_id, request_fingerprint, submitted_fields, result_resource_id, result_version, created_at, decided_at
`

type ContributionDecideParams struct {
	ID               pgtype.UUID
	Status           string
	ResultResourceID pgtype.UUID
	ResultVersion    pgtype.Int8
}

func (q *Queries) ContributionDecide(ctx context.Context, arg ContributionDecideParams) (AppContribution, error) {
	row := q.db.QueryRow(ctx, contributionDecide,
		arg.ID,
		arg.Status,
		arg.ResultResourceID,
		arg.ResultVersion,
	)
	var i AppContribution
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Kind,
		&i.TargetResourceID,
		&i.BaseVersion,
		&i.Status,
		&i.Reason,
		&i.PreviousID,
		&i.RequestID,
		&i.RequestFingerprint,
		&i.SubmittedFields,
		&i.ResultResourceID,
		&i.ResultVersion,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const contributionGet = `-- name: ContributionGet :one
SELECT id, author_id, kind, target_resource_id, base_version, status, reason, previous_id, request_id, request_fingerprint, submitted_fields, result_resource_id, result_version, created_at, decided_at FROM app.contributions WHERE id=$1
`

func (q *Queries) ContributionGet(ctx context.Context, id pgtype.UUID) (AppContribution, error) {
	row := q.db.QueryRow(ctx, contributionGet, id)
	var i AppContribution
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Kind,
		&i.TargetResourceID,
		&i.BaseVersion,
		&i.Status,
		&i.Reason,
		&i.PreviousID,
		&i.RequestID,
		&i.RequestFingerprint,
		&i.SubmittedFields,
		&i.ResultResourceID,
		&i.ResultVersion,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const contributionListAdmin = `-- name: ContributionListAdmin :many
SELECT c.id, c.author_id, c.kind, c.target_resource_id, c.base_version, c.status, c.reason, c.previous_id, c.request_id, c.request_fingerprint, c.submitted_fields, c.result_resource_id, c.result_version, c.created_at, c.decided_at,p.name FROM app.contributions c JOIN app.contribution_contents p ON p.contribution_id=c.id AND p.content_kind='proposed'
WHERE ($1::text IS NULL OR c.status=$1) AND ($2::text IS NULL OR c.kind=$2)
ORDER BY c.created_at,c.id LIMIT $4::int OFFSET $3::bigint
`

type ContributionListAdminParams struct {
	Status     pgtype.Text
	Kind       pgtype.Text
	PageOffset int64
	FetchLimit int32
}

type ContributionListAdminRow struct {
	ID                 pgtype.UUID
	AuthorID           pgtype.UUID
	Kind               string
	TargetResourceID   pgtype.UUID
	BaseVersion        pgtype.Int8
	Status             string
	Reason             string
	PreviousID         pgtype.UUID
	RequestID          pgtype.UUID
	RequestFingerprint []byte
	SubmittedFields    int16
	ResultResourceID   pgtype.UUID
	ResultVersion      pgtype.Int8
	CreatedAt          pgtype.Timestamptz
	DecidedAt          pgtype.Timestamptz
	Name               string
}

func (q *Queries) ContributionListAdmin(ctx context.Context, arg ContributionListAdminParams) ([]ContributionListAdminRow, error) {
	rows, err := q.db.Query(ctx, contributionListAdmin,
		arg.Status,
		arg.Kind,
		arg.PageOffset,
		arg.FetchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContributionListAdminRow{}
	for rows.Next() {
		var i ContributionListAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Kind,
			&i.TargetResourceID,
			&i.BaseVersion,
			&i.Status,
			&i.Reason,
			&i.PreviousID,
			&i.RequestID,
			&i.RequestFingerprint,
			&i.SubmittedFields,
			&i.ResultResourceID,
			&i.ResultVersion,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contributionListOwned = `-- name: ContributionListOwned :many
SELECT c.id, c.author_id, c.kind, c.target_resource_id, c.base_version, c.status, c.reason, c.previous_id, c.request_id, c.request_fingerprint, c.submitted_fields, c.result_resource_id, c.result_version, c.created_at, c.decided_at,CASE WHEN c.kind='create_resource' OR (c.submitted_fields & 1)<>0 THEN p.name ELSE 'Resource correction' END::text AS name FROM app.contributions c JOIN app.contribution_contents p ON p.contribution_id=c.id AND p.content_kind='proposed'
WHERE c.author_id=$1 AND ($2::text IS NULL OR c.status=$2)
ORDER BY c.created_at DESC,c.id DESC LIMIT $4::int OFFSET $3::bigint
`

type ContributionListOwnedParams struct {
	AuthorID   pgtype.UUID
	Status     pgtype.Text
	PageOffset int64
	FetchLimit int32
}

type ContributionListOwnedRow struct {
	ID                 pgtype.UUID
	AuthorID           pgtype.UUID
	Kind               string
	TargetResourceID   pgtype.UUID
	BaseVersion        pgtype.Int8
	Status             string
	Reason             string
	PreviousID         pgtype.UUID
	RequestID          pgtype.UUID
	RequestFingerprint []byte
	SubmittedFields    int16
	ResultResourceID   pgtype.UUID
	ResultVersion      pgtype.Int8
	CreatedAt          pgtype.Timestamptz
	DecidedAt          pgtype.Timestamptz
	Name               string
}

func (q *Queries) ContributionListOwned(ctx context.Context, arg ContributionListOwnedParams) ([]ContributionListOwnedRow, error) {
	rows, err := q.db.Query(ctx, contributionListOwned,
		arg.AuthorID,
		arg.Status,
		arg.PageOffset,
		arg.FetchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContributionListOwnedRow{}
	for rows.Next() {
		var i ContributionListOwnedRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Kind,
			&i.TargetResourceID,
			&i.BaseVersion,
			&i.Status,
			&i.Reason,
			&i.PreviousID,
			&i.RequestID,
			&i.RequestFingerprint,
			&i.SubmittedFields,
			&i.ResultResourceID,
			&i.ResultVersion,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contributionLock = `-- name: ContributionLock :one
SELECT id, author_id, kind, target_resource_id, base_version, status, reason, previous_id, request_id, request_fingerprint, submitted_fields, result_resource_id, result_version, created_at, decided_at FROM app.contributions WHERE id=$1 FOR UPDATE
`

func (q *Queries) ContributionLock(ctx context.Context, id pgtype.UUID) (AppContribution, error) {
	row := q.db.QueryRow(ctx, contributionLock, id)
	var i AppContribution
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Kind,
		&i.TargetResourceID,
		&i.BaseVersion,
		&i.Status,
		&i.Reason,
		&i.PreviousID,
		&i.RequestID,
		&i.RequestFingerprint,
		&i.SubmittedFields,
		&i.ResultResourceID,
		&i.ResultVersion,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const contributionLockOwned = `-- name: ContributionLockOwned :one
SELECT id, author_id, kind, target_resource_id, base_version, status, reason, previous_id, request_id, request_fingerprint, submitted_fields, result_resource_id, result_version, created_at, decided_at FROM app.contributions WHERE id=$1 AND author_id=$2 FOR UPDATE
`

type ContributionLockOwnedParams struct {
	ID       pgtype.UUID
	AuthorID pgtype.UUID
}

func (q *Queries) ContributionLockOwned(ctx context.Context, arg ContributionLockOwnedParams) (AppContribution, error) {
	row := q.db.QueryRow(ctx, contributionLockOwned, arg.ID, arg.AuthorID)
	var i AppContribution
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Kind,
		&i.TargetResourceID,
		&i.BaseVersion,
		&i.Status,
		&i.Reason,
		&i.PreviousID,
		&i.RequestID,
		&i.RequestFingerprint,
		&i.SubmittedFields,
		&i.ResultResourceID,
		&i.ResultVersion,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const contributionOwned = `-- name: ContributionOwned :one
SELECT id, author_id, kind, target_resource_id, base_version, status, reason, previous_id, request_id, request_fingerprint, submitted_fields, result_resource_id, result_version, created_at, decided_at FROM app.contributions WHERE id=$1 AND author_id=$2
`

type ContributionOwnedParams struct {
	ID       pgtype.UUID
	AuthorID pgtype.UUID
}

func (q *Queries) ContributionOwned(ctx context.Context, arg ContributionOwnedParams) (AppContribution, error) {
	row := q.db.QueryRow(ctx, contributionOwned, arg.ID, arg.AuthorID)
	var i AppContribution
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Kind,
		&i.TargetResourceID,
		&i.BaseVersion,
		&i.Status,
		&i.Reason,
		&i.PreviousID,
		&i.RequestID,
		&i.RequestFingerprint,
		&i.SubmittedFields,
		&i.ResultResourceID,
		&i.ResultVersion,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const contributionPublicEvent = `-- name: ContributionPublicEvent :exec
INSERT INTO app.contribution_events(contribution_id,event_type,actor_id,message,occurred_at)
SELECT id,$2,$3,$4,coalesce(decided_at,created_at) FROM app.contributions WHERE id=$1
`

type ContributionPublicEventParams struct {
	ID        pgtype.UUID
	EventType string
	ActorID   pgtype.UUID
	Message   pgtype.Text
}

func (q *Queries) ContributionPublicEvent(ctx context.Context, arg ContributionPublicEventParams) error {
	_, err := q.db.Exec(ctx, contributionPublicEvent,
		arg.ID,
		arg.EventType,
		arg.ActorID,
		arg.Message,
	)
	return err
}

const contributionPublicHistory = `-- name: ContributionPublicHistory :many
SELECT event_type,message,occurred_at FROM app.contribution_events WHERE contribution_id=$1 ORDER BY occurred_at,event_type
`

type ContributionPublicHistoryRow struct {
	EventType  string
	Message    pgtype.Text
	OccurredAt pgtype.Timestamptz
}

func (q *Queries) ContributionPublicHistory(ctx context.Context, contributionID pgtype.UUID) ([]ContributionPublicHistoryRow, error) {
	rows, err := q.db.Query(ctx, contributionPublicHistory, contributionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContributionPublicHistoryRow{}
	for rows.Next() {
		var i ContributionPublicHistoryRow
		if err := rows.Scan(&i.EventType, &i.Message, &i.OccurredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contributionPutContent = `-- name: ContributionPutContent :exec
INSERT INTO app.contribution_contents(contribution_id,content_kind,default_locale,category_id,name,summary,description,lifecycle,content_rating,slug)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type ContributionPutContentParams struct {
	ContributionID pgtype.UUID
	ContentKind    string
	DefaultLocale  string
	CategoryID     pgtype.UUID
	Name           string
	Summary        pgtype.Text
	Description    pgtype.Text
	Lifecycle      string
	ContentRating  string
	Slug           pgtype.Text
}

func (q *Queries) ContributionPutContent(ctx context.Context, arg ContributionPutContentParams) error {
	_, err := q.db.Exec(ctx, contributionPutContent,
		arg.ContributionID,
		arg.ContentKind,
		arg.DefaultLocale,
		arg.CategoryID,
		arg.Name,
		arg.Summary,
		arg.Description,
		arg.Lifecycle,
		arg.ContentRating,
		arg.Slug,
	)
	return err
}

const contributionPutSource = `-- name: ContributionPutSource :exec
INSERT INTO app.contribution_initial_sources(contribution_id,content_kind,url,label,source_type,availability_state)
VALUES($1,$2,$3,$4,$5,$6)
`

type ContributionPutSourceParams struct {
	ContributionID    pgtype.UUID
	ContentKind       string
	Url               string
	Label             pgtype.Text
	SourceType        string
	AvailabilityState string
}

func (q *Queries) ContributionPutSource(ctx context.Context, arg ContributionPutSourceParams) error {
	_, err := q.db.Exec(ctx, contributionPutSource,
		arg.ContributionID,
		arg.ContentKind,
		arg.Url,
		arg.Label,
		arg.SourceType,
		arg.AvailabilityState,
	)
	return err
}

const contributionQuota = `-- name: ContributionQuota :one
SELECT count(*) FILTER (WHERE created_at > $1::timestamptz - interval '24 hours')::bigint AS recent,
    count(*) FILTER (WHERE status='pending')::bigint AS pending,
    coalesce(max(created_at),'epoch'::timestamptz)::timestamptz AS last_at,
    coalesce(min(created_at) FILTER (WHERE created_at > $1::timestamptz - interval '24 hours'),$1::timestamptz)::timestamptz AS first_at
FROM app.contributions WHERE author_id=$2
`

type ContributionQuotaParams struct {
	Now      pgtype.Timestamptz
	AuthorID pgtype.UUID
}

type ContributionQuotaRow struct {
	Recent  int64
	Pending int64
	LastAt  pgtype.Timestamptz
	FirstAt pgtype.Timestamptz
}

func (q *Queries) ContributionQuota(ctx context.Context, arg ContributionQuotaParams) (ContributionQuotaRow, error) {
	row := q.db.QueryRow(ctx, contributionQuota, arg.Now, arg.AuthorID)
	var i ContributionQuotaRow
	err := row.Scan(
		&i.Recent,
		&i.Pending,
		&i.LastAt,
		&i.FirstAt,
	)
	return i, err
}

const contributionResource = `-- name: ContributionResource :one
SELECT r.id,r.slug,r.default_locale,r.category_id,r.lifecycle,r.content_rating,r.version,
    l.name,l.summary,l.description,(l.resource_id IS NOT NULL AND cl.category_id IS NOT NULL)::boolean AS canonical_ok
FROM app.resources r JOIN app.categories c ON c.id=r.category_id
LEFT JOIN app.resource_localizations l ON l.resource_id=r.id AND l.locale=r.default_locale
LEFT JOIN app.category_localizations cl ON cl.category_id=c.id AND cl.locale=c.default_locale
WHERE r.publication_state='published' AND r.deleted_at IS NULL AND c.deleted_at IS NULL
AND (($1::uuid IS NOT NULL AND r.id=$1) OR ($2::text IS NOT NULL AND r.slug=$2))
`

type ContributionResourceParams struct {
	ID   pgtype.UUID
	Slug pgtype.Text
}

type ContributionResourceRow struct {
	ID            pgtype.UUID
	Slug          string
	DefaultLocale string
	CategoryID    pgtype.UUID
	Lifecycle     string
	ContentRating string
	Version       int64
	Name          pgtype.Text
	Summary       pgtype.Text
	Description   pgtype.Text
	CanonicalOk   bool
}

func (q *Queries) ContributionResource(ctx context.Context, arg ContributionResourceParams) (ContributionResourceRow, error) {
	row := q.db.QueryRow(ctx, contributionResource, arg.ID, arg.Slug)
	var i ContributionResourceRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DefaultLocale,
		&i.CategoryID,
		&i.Lifecycle,
		&i.ContentRating,
		&i.Version,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.CanonicalOk,
	)
	return i, err
}

const contributionReviewEvent = `-- name: ContributionReviewEvent :exec
INSERT INTO app.contribution_events(contribution_id,event_type,actor_id,message,internal_note,occurred_at)
SELECT id,$2,$3,$4,$5,decided_at FROM app.contributions WHERE id=$1
`

type ContributionReviewEventParams struct {
	ID           pgtype.UUID
	EventType    string
	ActorID      pgtype.UUID
	Message      pgtype.Text
	InternalNote pgtype.Text
}

func (q *Queries) ContributionReviewEvent(ctx context.Context, arg ContributionReviewEventParams) error {
	_, err := q.db.Exec(ctx, contributionReviewEvent,
		arg.ID,
		arg.EventType,
		arg.ActorID,
		arg.Message,
		arg.InternalNote,
	)
	return err
}

const contributionVerified = `-- name: ContributionVerified :one
SELECT EXISTS(SELECT 1 FROM app.auth_identities WHERE user_id=$1 AND provider='email' AND verified_at IS NOT NULL)
`

func (q *Queries) ContributionVerified(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, contributionVerified, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const contributionWithdraw = `-- name: ContributionWithdraw :execrows
UPDATE app.contributions SET status='withdrawn',decided_at=clock_timestamp()
WHERE id=$1 AND author_id=$2 AND status='pending'
`

type ContributionWithdrawParams struct {
	ID       pgtype.UUID
	AuthorID pgtype.UUID
}

func (q *Queries) ContributionWithdraw(ctx context.Context, arg ContributionWithdrawParams) (int64, error) {
	result, err := q.db.Exec(ctx, contributionWithdraw, arg.ID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
