// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contribution_changes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const contributionAuditResource = `-- name: ContributionAuditResource :exec
INSERT INTO app.contribution_review_resource_changes(contribution_id,resource_id,before_version,after_version) VALUES($1,$2,$3,$4)
`

type ContributionAuditResourceParams struct {
	ContributionID pgtype.UUID
	ResourceID     pgtype.UUID
	BeforeVersion  int64
	AfterVersion   int64
}

func (q *Queries) ContributionAuditResource(ctx context.Context, arg ContributionAuditResourceParams) error {
	_, err := q.db.Exec(ctx, contributionAuditResource,
		arg.ContributionID,
		arg.ResourceID,
		arg.BeforeVersion,
		arg.AfterVersion,
	)
	return err
}

const contributionLocalizationChanges = `-- name: ContributionLocalizationChanges :many
SELECT contribution_id, snapshot_kind, locale, row_exists, name, summary, description, supplied_fields FROM app.contribution_localization_changes WHERE contribution_id=$1 ORDER BY snapshot_kind
`

func (q *Queries) ContributionLocalizationChanges(ctx context.Context, contributionID pgtype.UUID) ([]AppContributionLocalizationChange, error) {
	rows, err := q.db.Query(ctx, contributionLocalizationChanges, contributionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppContributionLocalizationChange{}
	for rows.Next() {
		var i AppContributionLocalizationChange
		if err := rows.Scan(
			&i.ContributionID,
			&i.SnapshotKind,
			&i.Locale,
			&i.RowExists,
			&i.Name,
			&i.Summary,
			&i.Description,
			&i.SuppliedFields,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contributionPublicSource = `-- name: ContributionPublicSource :one
SELECT id,url,label,source_type,availability_state FROM app.resource_sources
WHERE id=$1 AND resource_id=$2 AND availability_state<>'removed' AND rights_status IN ('unknown','creator_provided','confirmed')
`

type ContributionPublicSourceParams struct {
	ID         pgtype.UUID
	ResourceID pgtype.UUID
}

type ContributionPublicSourceRow struct {
	ID                pgtype.UUID
	Url               string
	Label             pgtype.Text
	SourceType        string
	AvailabilityState string
}

func (q *Queries) ContributionPublicSource(ctx context.Context, arg ContributionPublicSourceParams) (ContributionPublicSourceRow, error) {
	row := q.db.QueryRow(ctx, contributionPublicSource, arg.ID, arg.ResourceID)
	var i ContributionPublicSourceRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Label,
		&i.SourceType,
		&i.AvailabilityState,
	)
	return i, err
}

const contributionPutAcceptedRelation = `-- name: ContributionPutAcceptedRelation :exec
INSERT INTO app.contribution_relation_changes(contribution_id,snapshot_kind,other_resource_id,relation_type,direction,other_base_version,anchor_result_version,other_result_version)
VALUES($1,'accepted',$2,$3,$4,$5,$6,$7)
`

type ContributionPutAcceptedRelationParams struct {
	ContributionID      pgtype.UUID
	OtherResourceID     pgtype.UUID
	RelationType        string
	Direction           string
	OtherBaseVersion    int64
	AnchorResultVersion pgtype.Int8
	OtherResultVersion  pgtype.Int8
}

func (q *Queries) ContributionPutAcceptedRelation(ctx context.Context, arg ContributionPutAcceptedRelationParams) error {
	_, err := q.db.Exec(ctx, contributionPutAcceptedRelation,
		arg.ContributionID,
		arg.OtherResourceID,
		arg.RelationType,
		arg.Direction,
		arg.OtherBaseVersion,
		arg.AnchorResultVersion,
		arg.OtherResultVersion,
	)
	return err
}

const contributionPutLocalizationChange = `-- name: ContributionPutLocalizationChange :exec
INSERT INTO app.contribution_localization_changes(contribution_id,snapshot_kind,locale,row_exists,name,summary,description,supplied_fields) VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type ContributionPutLocalizationChangeParams struct {
	ContributionID pgtype.UUID
	SnapshotKind   string
	Locale         string
	RowExists      bool
	Name           pgtype.Text
	Summary        pgtype.Text
	Description    pgtype.Text
	SuppliedFields int16
}

func (q *Queries) ContributionPutLocalizationChange(ctx context.Context, arg ContributionPutLocalizationChangeParams) error {
	_, err := q.db.Exec(ctx, contributionPutLocalizationChange,
		arg.ContributionID,
		arg.SnapshotKind,
		arg.Locale,
		arg.RowExists,
		arg.Name,
		arg.Summary,
		arg.Description,
		arg.SuppliedFields,
	)
	return err
}

const contributionPutRelationChange = `-- name: ContributionPutRelationChange :exec
INSERT INTO app.contribution_relation_changes(contribution_id,snapshot_kind,other_resource_id,relation_type,direction,other_base_version) VALUES($1,$2,$3,$4,$5,$6)
`

type ContributionPutRelationChangeParams struct {
	ContributionID   pgtype.UUID
	SnapshotKind     string
	OtherResourceID  pgtype.UUID
	RelationType     string
	Direction        string
	OtherBaseVersion int64
}

func (q *Queries) ContributionPutRelationChange(ctx context.Context, arg ContributionPutRelationChangeParams) error {
	_, err := q.db.Exec(ctx, contributionPutRelationChange,
		arg.ContributionID,
		arg.SnapshotKind,
		arg.OtherResourceID,
		arg.RelationType,
		arg.Direction,
		arg.OtherBaseVersion,
	)
	return err
}

const contributionPutSourceChange = `-- name: ContributionPutSourceChange :exec
INSERT INTO app.contribution_source_changes(contribution_id,snapshot_kind,source_id,url,label,source_type,availability_state) VALUES($1,$2,$3,$4,$5,$6,$7)
`

type ContributionPutSourceChangeParams struct {
	ContributionID    pgtype.UUID
	SnapshotKind      string
	SourceID          pgtype.UUID
	Url               pgtype.Text
	Label             pgtype.Text
	SourceType        pgtype.Text
	AvailabilityState pgtype.Text
}

func (q *Queries) ContributionPutSourceChange(ctx context.Context, arg ContributionPutSourceChangeParams) error {
	_, err := q.db.Exec(ctx, contributionPutSourceChange,
		arg.ContributionID,
		arg.SnapshotKind,
		arg.SourceID,
		arg.Url,
		arg.Label,
		arg.SourceType,
		arg.AvailabilityState,
	)
	return err
}

const contributionPutTagChange = `-- name: ContributionPutTagChange :exec
INSERT INTO app.contribution_tag_changes(contribution_id,snapshot_kind,tag_id,was_bound) VALUES($1,$2,$3,$4)
`

type ContributionPutTagChangeParams struct {
	ContributionID pgtype.UUID
	SnapshotKind   string
	TagID          pgtype.UUID
	WasBound       bool
}

func (q *Queries) ContributionPutTagChange(ctx context.Context, arg ContributionPutTagChangeParams) error {
	_, err := q.db.Exec(ctx, contributionPutTagChange,
		arg.ContributionID,
		arg.SnapshotKind,
		arg.TagID,
		arg.WasBound,
	)
	return err
}

const contributionRelationChanges = `-- name: ContributionRelationChanges :many
SELECT contribution_id, snapshot_kind, other_resource_id, relation_type, direction, other_base_version, anchor_result_version, other_result_version FROM app.contribution_relation_changes WHERE contribution_id=$1 ORDER BY snapshot_kind
`

func (q *Queries) ContributionRelationChanges(ctx context.Context, contributionID pgtype.UUID) ([]AppContributionRelationChange, error) {
	rows, err := q.db.Query(ctx, contributionRelationChanges, contributionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppContributionRelationChange{}
	for rows.Next() {
		var i AppContributionRelationChange
		if err := rows.Scan(
			&i.ContributionID,
			&i.SnapshotKind,
			&i.OtherResourceID,
			&i.RelationType,
			&i.Direction,
			&i.OtherBaseVersion,
			&i.AnchorResultVersion,
			&i.OtherResultVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contributionRelationExists = `-- name: ContributionRelationExists :one
SELECT EXISTS(SELECT 1 FROM app.resource_relations WHERE source_resource_id=$1 AND target_resource_id=$2 AND relation_type=$3)
`

type ContributionRelationExistsParams struct {
	SourceResourceID pgtype.UUID
	TargetResourceID pgtype.UUID
	RelationType     string
}

func (q *Queries) ContributionRelationExists(ctx context.Context, arg ContributionRelationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, contributionRelationExists, arg.SourceResourceID, arg.TargetResourceID, arg.RelationType)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const contributionResourceAudits = `-- name: ContributionResourceAudits :many
SELECT contribution_id, resource_id, before_version, after_version FROM app.contribution_review_resource_changes WHERE contribution_id=$1 ORDER BY resource_id
`

func (q *Queries) ContributionResourceAudits(ctx context.Context, contributionID pgtype.UUID) ([]AppContributionReviewResourceChange, error) {
	rows, err := q.db.Query(ctx, contributionResourceAudits, contributionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppContributionReviewResourceChange{}
	for rows.Next() {
		var i AppContributionReviewResourceChange
		if err := rows.Scan(
			&i.ContributionID,
			&i.ResourceID,
			&i.BeforeVersion,
			&i.AfterVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contributionSourceChanges = `-- name: ContributionSourceChanges :many
SELECT contribution_id, snapshot_kind, source_id, url, label, source_type, availability_state FROM app.contribution_source_changes WHERE contribution_id=$1 ORDER BY snapshot_kind
`

func (q *Queries) ContributionSourceChanges(ctx context.Context, contributionID pgtype.UUID) ([]AppContributionSourceChange, error) {
	rows, err := q.db.Query(ctx, contributionSourceChanges, contributionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppContributionSourceChange{}
	for rows.Next() {
		var i AppContributionSourceChange
		if err := rows.Scan(
			&i.ContributionID,
			&i.SnapshotKind,
			&i.SourceID,
			&i.Url,
			&i.Label,
			&i.SourceType,
			&i.AvailabilityState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contributionSourceURLExists = `-- name: ContributionSourceURLExists :one
SELECT EXISTS(SELECT 1 FROM app.resource_sources WHERE resource_id=$1 AND url=$2)
`

type ContributionSourceURLExistsParams struct {
	ResourceID pgtype.UUID
	Url        string
}

func (q *Queries) ContributionSourceURLExists(ctx context.Context, arg ContributionSourceURLExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, contributionSourceURLExists, arg.ResourceID, arg.Url)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const contributionTagChanges = `-- name: ContributionTagChanges :many
SELECT contribution_id, snapshot_kind, tag_id, was_bound FROM app.contribution_tag_changes WHERE contribution_id=$1 ORDER BY snapshot_kind,tag_id
`

func (q *Queries) ContributionTagChanges(ctx context.Context, contributionID pgtype.UUID) ([]AppContributionTagChange, error) {
	rows, err := q.db.Query(ctx, contributionTagChanges, contributionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppContributionTagChange{}
	for rows.Next() {
		var i AppContributionTagChange
		if err := rows.Scan(
			&i.ContributionID,
			&i.SnapshotKind,
			&i.TagID,
			&i.WasBound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contributionTagState = `-- name: ContributionTagState :one
SELECT t.state,l.name,(l.tag_id IS NOT NULL)::boolean AS canonical_ok,
 EXISTS(SELECT 1 FROM app.resource_tags rt WHERE rt.resource_id=$2 AND rt.tag_id=t.id)::boolean AS bound
FROM app.tags t LEFT JOIN app.tag_localizations l ON l.tag_id=t.id AND l.locale=t.default_locale WHERE t.id=$1 AND t.deleted_at IS NULL
`

type ContributionTagStateParams struct {
	ID         pgtype.UUID
	ResourceID pgtype.UUID
}

type ContributionTagStateRow struct {
	State       string
	Name        pgtype.Text
	CanonicalOk bool
	Bound       bool
}

func (q *Queries) ContributionTagState(ctx context.Context, arg ContributionTagStateParams) (ContributionTagStateRow, error) {
	row := q.db.QueryRow(ctx, contributionTagState, arg.ID, arg.ResourceID)
	var i ContributionTagStateRow
	err := row.Scan(
		&i.State,
		&i.Name,
		&i.CanonicalOk,
		&i.Bound,
	)
	return i, err
}

const contributionTranslation = `-- name: ContributionTranslation :one
SELECT resource_id, locale, name, summary, description, created_at, updated_at FROM app.resource_localizations WHERE resource_id=$1 AND locale=$2
`

type ContributionTranslationParams struct {
	ResourceID pgtype.UUID
	Locale     string
}

func (q *Queries) ContributionTranslation(ctx context.Context, arg ContributionTranslationParams) (AppResourceLocalization, error) {
	row := q.db.QueryRow(ctx, contributionTranslation, arg.ResourceID, arg.Locale)
	var i AppResourceLocalization
	err := row.Scan(
		&i.ResourceID,
		&i.Locale,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
