// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: curation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const curationAddExternalID = `-- name: CurationAddExternalID :exec
INSERT INTO app.resource_external_ids(resource_id,namespace,external_id,created_at) VALUES($1,$2,$3,transaction_timestamp())
`

type CurationAddExternalIDParams struct {
	ResourceID pgtype.UUID
	Namespace  string
	ExternalID string
}

func (q *Queries) CurationAddExternalID(ctx context.Context, arg CurationAddExternalIDParams) error {
	_, err := q.db.Exec(ctx, curationAddExternalID, arg.ResourceID, arg.Namespace, arg.ExternalID)
	return err
}

const curationAddRelation = `-- name: CurationAddRelation :execrows
INSERT INTO app.resource_relations(id,source_resource_id,target_resource_id,relation_type,created_at)
VALUES($1,$2,$3,$4,transaction_timestamp()) ON CONFLICT(source_resource_id,target_resource_id,relation_type) DO NOTHING
`

type CurationAddRelationParams struct {
	ID               pgtype.UUID
	SourceResourceID pgtype.UUID
	TargetResourceID pgtype.UUID
	RelationType     string
}

func (q *Queries) CurationAddRelation(ctx context.Context, arg CurationAddRelationParams) (int64, error) {
	result, err := q.db.Exec(ctx, curationAddRelation,
		arg.ID,
		arg.SourceResourceID,
		arg.TargetResourceID,
		arg.RelationType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const curationAddTag = `-- name: CurationAddTag :exec
INSERT INTO app.resource_tags(resource_id,tag_id) VALUES($1,$2)
`

type CurationAddTagParams struct {
	ResourceID pgtype.UUID
	TagID      pgtype.UUID
}

func (q *Queries) CurationAddTag(ctx context.Context, arg CurationAddTagParams) error {
	_, err := q.db.Exec(ctx, curationAddTag, arg.ResourceID, arg.TagID)
	return err
}

const curationBumpRevision = `-- name: CurationBumpRevision :one
UPDATE app.resources SET version=version+1,updated_at=transaction_timestamp()
WHERE id=$1 AND version=$2 RETURNING version
`

type CurationBumpRevisionParams struct {
	ID      pgtype.UUID
	Version int64
}

func (q *Queries) CurationBumpRevision(ctx context.Context, arg CurationBumpRevisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, curationBumpRevision, arg.ID, arg.Version)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const curationCategoryInUse = `-- name: CurationCategoryInUse :one
SELECT EXISTS(SELECT 1 FROM app.resources r
 WHERE r.category_id=$1 AND r.deleted_at IS NULL)
`

func (q *Queries) CurationCategoryInUse(ctx context.Context, categoryID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, curationCategoryInUse, categoryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const curationClearPrimary = `-- name: CurationClearPrimary :exec
UPDATE app.resource_sources SET is_primary=false,updated_at=transaction_timestamp() WHERE resource_id=$1 AND is_primary AND id<>$2
`

type CurationClearPrimaryParams struct {
	ResourceID pgtype.UUID
	ID         pgtype.UUID
}

func (q *Queries) CurationClearPrimary(ctx context.Context, arg CurationClearPrimaryParams) error {
	_, err := q.db.Exec(ctx, curationClearPrimary, arg.ResourceID, arg.ID)
	return err
}

const curationCreateCategory = `-- name: CurationCreateCategory :exec
INSERT INTO app.categories(id,slug,default_locale,state,created_at,updated_at)
VALUES($1,$2,$3,'active',transaction_timestamp(),transaction_timestamp())
`

type CurationCreateCategoryParams struct {
	ID            pgtype.UUID
	Slug          string
	DefaultLocale string
}

func (q *Queries) CurationCreateCategory(ctx context.Context, arg CurationCreateCategoryParams) error {
	_, err := q.db.Exec(ctx, curationCreateCategory, arg.ID, arg.Slug, arg.DefaultLocale)
	return err
}

const curationCreateResource = `-- name: CurationCreateResource :exec
INSERT INTO app.resources(id,slug,default_locale,category_id,publication_state,lifecycle,content_rating,version,created_at,updated_at)
VALUES($1,$2,$3,$4,'draft',$5,$6,1,transaction_timestamp(),transaction_timestamp())
`

type CurationCreateResourceParams struct {
	ID            pgtype.UUID
	Slug          string
	DefaultLocale string
	CategoryID    pgtype.UUID
	Lifecycle     string
	ContentRating string
}

func (q *Queries) CurationCreateResource(ctx context.Context, arg CurationCreateResourceParams) error {
	_, err := q.db.Exec(ctx, curationCreateResource,
		arg.ID,
		arg.Slug,
		arg.DefaultLocale,
		arg.CategoryID,
		arg.Lifecycle,
		arg.ContentRating,
	)
	return err
}

const curationCreateSource = `-- name: CurationCreateSource :exec
INSERT INTO app.resource_sources(id,resource_id,url,label,source_type,availability_state,rights_status,is_primary,created_at,updated_at)
VALUES($1,$2,$3,$4,$5,$6,'unknown',$7,transaction_timestamp(),transaction_timestamp())
`

type CurationCreateSourceParams struct {
	ID                pgtype.UUID
	ResourceID        pgtype.UUID
	Url               string
	Label             pgtype.Text
	SourceType        string
	AvailabilityState string
	IsPrimary         bool
}

func (q *Queries) CurationCreateSource(ctx context.Context, arg CurationCreateSourceParams) error {
	_, err := q.db.Exec(ctx, curationCreateSource,
		arg.ID,
		arg.ResourceID,
		arg.Url,
		arg.Label,
		arg.SourceType,
		arg.AvailabilityState,
		arg.IsPrimary,
	)
	return err
}

const curationCreateTag = `-- name: CurationCreateTag :exec
INSERT INTO app.tags(id,slug,default_locale,state,created_at,updated_at)
VALUES($1,$2,$3,'active',transaction_timestamp(),transaction_timestamp())
`

type CurationCreateTagParams struct {
	ID            pgtype.UUID
	Slug          string
	DefaultLocale string
}

func (q *Queries) CurationCreateTag(ctx context.Context, arg CurationCreateTagParams) error {
	_, err := q.db.Exec(ctx, curationCreateTag, arg.ID, arg.Slug, arg.DefaultLocale)
	return err
}

const curationCurrentTags = `-- name: CurationCurrentTags :many
SELECT tag_id FROM app.resource_tags WHERE resource_id=$1 ORDER BY tag_id
`

func (q *Queries) CurationCurrentTags(ctx context.Context, resourceID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, curationCurrentTags, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var tag_id pgtype.UUID
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const curationDeleteCategoryLocalization = `-- name: CurationDeleteCategoryLocalization :execrows
DELETE FROM app.category_localizations WHERE category_id=$1 AND locale=$2
`

type CurationDeleteCategoryLocalizationParams struct {
	CategoryID pgtype.UUID
	Locale     string
}

func (q *Queries) CurationDeleteCategoryLocalization(ctx context.Context, arg CurationDeleteCategoryLocalizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, curationDeleteCategoryLocalization, arg.CategoryID, arg.Locale)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const curationDeleteLocalization = `-- name: CurationDeleteLocalization :execrows
DELETE FROM app.resource_localizations WHERE resource_id=$1 AND locale=$2
`

type CurationDeleteLocalizationParams struct {
	ResourceID pgtype.UUID
	Locale     string
}

func (q *Queries) CurationDeleteLocalization(ctx context.Context, arg CurationDeleteLocalizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, curationDeleteLocalization, arg.ResourceID, arg.Locale)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const curationDeleteRelation = `-- name: CurationDeleteRelation :execrows
DELETE FROM app.resource_relations WHERE id=$1
`

func (q *Queries) CurationDeleteRelation(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, curationDeleteRelation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const curationDeleteTagLocalization = `-- name: CurationDeleteTagLocalization :execrows
DELETE FROM app.tag_localizations WHERE tag_id=$1 AND locale=$2
`

type CurationDeleteTagLocalizationParams struct {
	TagID  pgtype.UUID
	Locale string
}

func (q *Queries) CurationDeleteTagLocalization(ctx context.Context, arg CurationDeleteTagLocalizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, curationDeleteTagLocalization, arg.TagID, arg.Locale)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const curationGetRelation = `-- name: CurationGetRelation :one
SELECT id, source_resource_id, target_resource_id, relation_type, created_at FROM app.resource_relations WHERE id=$1
`

func (q *Queries) CurationGetRelation(ctx context.Context, id pgtype.UUID) (AppResourceRelation, error) {
	row := q.db.QueryRow(ctx, curationGetRelation, id)
	var i AppResourceRelation
	err := row.Scan(
		&i.ID,
		&i.SourceResourceID,
		&i.TargetResourceID,
		&i.RelationType,
		&i.CreatedAt,
	)
	return i, err
}

const curationGetSource = `-- name: CurationGetSource :one
SELECT id, resource_id, url, label, source_type, availability_state, rights_status, is_primary, created_at, updated_at FROM app.resource_sources WHERE id=$1 AND resource_id=$2
`

type CurationGetSourceParams struct {
	ID         pgtype.UUID
	ResourceID pgtype.UUID
}

func (q *Queries) CurationGetSource(ctx context.Context, arg CurationGetSourceParams) (AppResourceSource, error) {
	row := q.db.QueryRow(ctx, curationGetSource, arg.ID, arg.ResourceID)
	var i AppResourceSource
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.Url,
		&i.Label,
		&i.SourceType,
		&i.AvailabilityState,
		&i.RightsStatus,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const curationLockCategory = `-- name: CurationLockCategory :one
SELECT id, slug, default_locale, state, created_at, updated_at, deleted_at FROM app.categories WHERE id=$1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) CurationLockCategory(ctx context.Context, id pgtype.UUID) (AppCategory, error) {
	row := q.db.QueryRow(ctx, curationLockCategory, id)
	var i AppCategory
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DefaultLocale,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const curationLockRelationGraph = `-- name: CurationLockRelationGraph :exec
SELECT pg_advisory_xact_lock(72463159018202)
`

func (q *Queries) CurationLockRelationGraph(ctx context.Context) error {
	_, err := q.db.Exec(ctx, curationLockRelationGraph)
	return err
}

const curationLockTag = `-- name: CurationLockTag :one
SELECT id, slug, default_locale, state, created_at, updated_at, deleted_at FROM app.tags WHERE id=$1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) CurationLockTag(ctx context.Context, id pgtype.UUID) (AppTag, error) {
	row := q.db.QueryRow(ctx, curationLockTag, id)
	var i AppTag
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DefaultLocale,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const curationPublish = `-- name: CurationPublish :exec
UPDATE app.resources SET publication_state=$1,
 published_at=CASE WHEN $1::text='published' AND published_at IS NULL THEN transaction_timestamp() ELSE published_at END
WHERE id=$2
`

type CurationPublishParams struct {
	State string
	ID    pgtype.UUID
}

func (q *Queries) CurationPublish(ctx context.Context, arg CurationPublishParams) error {
	_, err := q.db.Exec(ctx, curationPublish, arg.State, arg.ID)
	return err
}

const curationPutCategoryLocalization = `-- name: CurationPutCategoryLocalization :execrows
INSERT INTO app.category_localizations(category_id,locale,name,description,created_at,updated_at)
VALUES($1,$2,$3,$4,transaction_timestamp(),transaction_timestamp())
ON CONFLICT(category_id,locale) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,updated_at=transaction_timestamp()
WHERE (category_localizations.name,category_localizations.description) IS DISTINCT FROM (EXCLUDED.name,EXCLUDED.description)
`

type CurationPutCategoryLocalizationParams struct {
	CategoryID  pgtype.UUID
	Locale      string
	Name        string
	Description pgtype.Text
}

func (q *Queries) CurationPutCategoryLocalization(ctx context.Context, arg CurationPutCategoryLocalizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, curationPutCategoryLocalization,
		arg.CategoryID,
		arg.Locale,
		arg.Name,
		arg.Description,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const curationPutLocalization = `-- name: CurationPutLocalization :execrows
INSERT INTO app.resource_localizations(resource_id,locale,name,summary,description,created_at,updated_at)
VALUES($1,$2,$3,$4,$5,transaction_timestamp(),transaction_timestamp())
ON CONFLICT(resource_id,locale) DO UPDATE SET name=EXCLUDED.name,summary=EXCLUDED.summary,description=EXCLUDED.description,updated_at=transaction_timestamp()
WHERE (resource_localizations.name,resource_localizations.summary,resource_localizations.description) IS DISTINCT FROM (EXCLUDED.name,EXCLUDED.summary,EXCLUDED.description)
`

type CurationPutLocalizationParams struct {
	ResourceID  pgtype.UUID
	Locale      string
	Name        string
	Summary     pgtype.Text
	Description pgtype.Text
}

func (q *Queries) CurationPutLocalization(ctx context.Context, arg CurationPutLocalizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, curationPutLocalization,
		arg.ResourceID,
		arg.Locale,
		arg.Name,
		arg.Summary,
		arg.Description,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const curationPutTagLocalization = `-- name: CurationPutTagLocalization :execrows
INSERT INTO app.tag_localizations(tag_id,locale,name,description,created_at,updated_at)
VALUES($1,$2,$3,$4,transaction_timestamp(),transaction_timestamp())
ON CONFLICT(tag_id,locale) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,updated_at=transaction_timestamp()
WHERE (tag_localizations.name,tag_localizations.description) IS DISTINCT FROM (EXCLUDED.name,EXCLUDED.description)
`

type CurationPutTagLocalizationParams struct {
	TagID       pgtype.UUID
	Locale      string
	Name        string
	Description pgtype.Text
}

func (q *Queries) CurationPutTagLocalization(ctx context.Context, arg CurationPutTagLocalizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, curationPutTagLocalization,
		arg.TagID,
		arg.Locale,
		arg.Name,
		arg.Description,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const curationRelationCycle = `-- name: CurationRelationCycle :one
WITH RECURSIVE reachable(id) AS (
 SELECT $2::uuid
 UNION
 SELECT rr.target_resource_id FROM app.resource_relations rr JOIN reachable r ON rr.source_resource_id=r.id
 WHERE rr.relation_type=$3
)
SELECT EXISTS(SELECT 1 FROM reachable WHERE id=$1::uuid)
`

type CurationRelationCycleParams struct {
	SourceID     pgtype.UUID
	TargetID     pgtype.UUID
	RelationType string
}

func (q *Queries) CurationRelationCycle(ctx context.Context, arg CurationRelationCycleParams) (bool, error) {
	row := q.db.QueryRow(ctx, curationRelationCycle, arg.SourceID, arg.TargetID, arg.RelationType)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const curationRemoveExternalID = `-- name: CurationRemoveExternalID :exec
DELETE FROM app.resource_external_ids WHERE resource_id=$1 AND namespace=$2 AND external_id=$3
`

type CurationRemoveExternalIDParams struct {
	ResourceID pgtype.UUID
	Namespace  string
	ExternalID string
}

func (q *Queries) CurationRemoveExternalID(ctx context.Context, arg CurationRemoveExternalIDParams) error {
	_, err := q.db.Exec(ctx, curationRemoveExternalID, arg.ResourceID, arg.Namespace, arg.ExternalID)
	return err
}

const curationRemoveTag = `-- name: CurationRemoveTag :exec
DELETE FROM app.resource_tags WHERE resource_id=$1 AND tag_id=$2
`

type CurationRemoveTagParams struct {
	ResourceID pgtype.UUID
	TagID      pgtype.UUID
}

func (q *Queries) CurationRemoveTag(ctx context.Context, arg CurationRemoveTagParams) error {
	_, err := q.db.Exec(ctx, curationRemoveTag, arg.ResourceID, arg.TagID)
	return err
}

const curationSoftDeleteCategory = `-- name: CurationSoftDeleteCategory :exec
UPDATE app.categories SET deleted_at=transaction_timestamp(),updated_at=transaction_timestamp() WHERE id=$1
`

func (q *Queries) CurationSoftDeleteCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, curationSoftDeleteCategory, id)
	return err
}

const curationSoftDeleteResource = `-- name: CurationSoftDeleteResource :exec
UPDATE app.resources SET deleted_at=transaction_timestamp() WHERE id=$1
`

func (q *Queries) CurationSoftDeleteResource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, curationSoftDeleteResource, id)
	return err
}

const curationSoftDeleteTag = `-- name: CurationSoftDeleteTag :exec
UPDATE app.tags SET deleted_at=transaction_timestamp(),updated_at=transaction_timestamp() WHERE id=$1
`

func (q *Queries) CurationSoftDeleteTag(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, curationSoftDeleteTag, id)
	return err
}

const curationSourceRights = `-- name: CurationSourceRights :execrows
UPDATE app.resource_sources SET rights_status=$2,updated_at=transaction_timestamp() WHERE id=$1 AND rights_status<>$2
`

type CurationSourceRightsParams struct {
	ID           pgtype.UUID
	RightsStatus string
}

func (q *Queries) CurationSourceRights(ctx context.Context, arg CurationSourceRightsParams) (int64, error) {
	result, err := q.db.Exec(ctx, curationSourceRights, arg.ID, arg.RightsStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const curationTagInUse = `-- name: CurationTagInUse :one
SELECT EXISTS(SELECT 1 FROM app.resources r JOIN app.resource_tags rt ON rt.resource_id=r.id
 WHERE rt.tag_id=$1 AND r.deleted_at IS NULL)
`

func (q *Queries) CurationTagInUse(ctx context.Context, tagID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, curationTagInUse, tagID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const curationTouchCategory = `-- name: CurationTouchCategory :exec
UPDATE app.categories SET updated_at=transaction_timestamp() WHERE id=$1
`

func (q *Queries) CurationTouchCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, curationTouchCategory, id)
	return err
}

const curationTouchTag = `-- name: CurationTouchTag :exec
UPDATE app.tags SET updated_at=transaction_timestamp() WHERE id=$1
`

func (q *Queries) CurationTouchTag(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, curationTouchTag, id)
	return err
}

const curationUpdateCategory = `-- name: CurationUpdateCategory :exec
UPDATE app.categories SET default_locale=$2,state=$3,updated_at=transaction_timestamp() WHERE id=$1
`

type CurationUpdateCategoryParams struct {
	ID            pgtype.UUID
	DefaultLocale string
	State         string
}

func (q *Queries) CurationUpdateCategory(ctx context.Context, arg CurationUpdateCategoryParams) error {
	_, err := q.db.Exec(ctx, curationUpdateCategory, arg.ID, arg.DefaultLocale, arg.State)
	return err
}

const curationUpdateCore = `-- name: CurationUpdateCore :exec
UPDATE app.resources SET slug=$2,default_locale=$3,category_id=$4,lifecycle=$5,content_rating=$6 WHERE id=$1
`

type CurationUpdateCoreParams struct {
	ID            pgtype.UUID
	Slug          string
	DefaultLocale string
	CategoryID    pgtype.UUID
	Lifecycle     string
	ContentRating string
}

func (q *Queries) CurationUpdateCore(ctx context.Context, arg CurationUpdateCoreParams) error {
	_, err := q.db.Exec(ctx, curationUpdateCore,
		arg.ID,
		arg.Slug,
		arg.DefaultLocale,
		arg.CategoryID,
		arg.Lifecycle,
		arg.ContentRating,
	)
	return err
}

const curationUpdateSource = `-- name: CurationUpdateSource :execrows
UPDATE app.resource_sources SET url=$2,label=$3,source_type=$4,availability_state=$5,is_primary=$6,updated_at=transaction_timestamp()
WHERE id=$1 AND (url,label,source_type,availability_state,is_primary) IS DISTINCT FROM ($2,$3,$4,$5,$6)
`

type CurationUpdateSourceParams struct {
	ID                pgtype.UUID
	Url               string
	Label             pgtype.Text
	SourceType        string
	AvailabilityState string
	IsPrimary         bool
}

func (q *Queries) CurationUpdateSource(ctx context.Context, arg CurationUpdateSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, curationUpdateSource,
		arg.ID,
		arg.Url,
		arg.Label,
		arg.SourceType,
		arg.AvailabilityState,
		arg.IsPrimary,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const curationUpdateTag = `-- name: CurationUpdateTag :exec
UPDATE app.tags SET default_locale=$2,state=$3,updated_at=transaction_timestamp() WHERE id=$1
`

type CurationUpdateTagParams struct {
	ID            pgtype.UUID
	DefaultLocale string
	State         string
}

func (q *Queries) CurationUpdateTag(ctx context.Context, arg CurationUpdateTagParams) error {
	_, err := q.db.Exec(ctx, curationUpdateTag, arg.ID, arg.DefaultLocale, arg.State)
	return err
}
