// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: governance.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const governanceActionByRequest = `-- name: GovernanceActionByRequest :one
SELECT id, actor_id, action, resource_id, source_id, user_id, restriction_id, report_id, reason, internal_note, request_id, request_fingerprint, occurred_at FROM app.moderation_actions WHERE actor_id=$1 AND request_id=$2
`

type GovernanceActionByRequestParams struct {
	ActorID   pgtype.UUID
	RequestID pgtype.UUID
}

func (q *Queries) GovernanceActionByRequest(ctx context.Context, arg GovernanceActionByRequestParams) (AppModerationAction, error) {
	row := q.db.QueryRow(ctx, governanceActionByRequest, arg.ActorID, arg.RequestID)
	var i AppModerationAction
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.ResourceID,
		&i.SourceID,
		&i.UserID,
		&i.RestrictionID,
		&i.ReportID,
		&i.Reason,
		&i.InternalNote,
		&i.RequestID,
		&i.RequestFingerprint,
		&i.OccurredAt,
	)
	return i, err
}

const governanceAudit = `-- name: GovernanceAudit :one
SELECT id, actor_id, operation, resource_id, category_id, tag_id, user_id, source_id, contribution_id, moderation_action_id, fields, before_version, after_version, before_availability, after_availability, before_taxonomy_state, after_taxonomy_state, before_publication, after_publication, before_rights, after_rights, before_distribution, after_distribution, before_trust, after_trust, reason, occurred_at FROM app.audit_entries WHERE id=$1
`

func (q *Queries) GovernanceAudit(ctx context.Context, id pgtype.UUID) (AppAuditEntry, error) {
	row := q.db.QueryRow(ctx, governanceAudit, id)
	var i AppAuditEntry
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Operation,
		&i.ResourceID,
		&i.CategoryID,
		&i.TagID,
		&i.UserID,
		&i.SourceID,
		&i.ContributionID,
		&i.ModerationActionID,
		&i.Fields,
		&i.BeforeVersion,
		&i.AfterVersion,
		&i.BeforeAvailability,
		&i.AfterAvailability,
		&i.BeforeTaxonomyState,
		&i.AfterTaxonomyState,
		&i.BeforePublication,
		&i.AfterPublication,
		&i.BeforeRights,
		&i.AfterRights,
		&i.BeforeDistribution,
		&i.AfterDistribution,
		&i.BeforeTrust,
		&i.AfterTrust,
		&i.Reason,
		&i.OccurredAt,
	)
	return i, err
}

const governanceAuditList = `-- name: GovernanceAuditList :many
SELECT id, actor_id, operation, resource_id, category_id, tag_id, user_id, source_id, contribution_id, moderation_action_id, fields, before_version, after_version, before_availability, after_availability, before_taxonomy_state, after_taxonomy_state, before_publication, after_publication, before_rights, after_rights, before_distribution, after_distribution, before_trust, after_trust, reason, occurred_at FROM app.audit_entries
WHERE ($1::uuid IS NULL OR resource_id=$1)
AND ($2::uuid IS NULL OR user_id=$2)
AND ($3::text IS NULL OR operation=$3)
ORDER BY occurred_at DESC,id DESC LIMIT $5 OFFSET $4::bigint
`

type GovernanceAuditListParams struct {
	ResourceID pgtype.UUID
	UserID     pgtype.UUID
	Operation  pgtype.Text
	PageOffset int64
	FetchLimit int32
}

func (q *Queries) GovernanceAuditList(ctx context.Context, arg GovernanceAuditListParams) ([]AppAuditEntry, error) {
	rows, err := q.db.Query(ctx, governanceAuditList,
		arg.ResourceID,
		arg.UserID,
		arg.Operation,
		arg.PageOffset,
		arg.FetchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppAuditEntry{}
	for rows.Next() {
		var i AppAuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Operation,
			&i.ResourceID,
			&i.CategoryID,
			&i.TagID,
			&i.UserID,
			&i.SourceID,
			&i.ContributionID,
			&i.ModerationActionID,
			&i.Fields,
			&i.BeforeVersion,
			&i.AfterVersion,
			&i.BeforeAvailability,
			&i.AfterAvailability,
			&i.BeforeTaxonomyState,
			&i.AfterTaxonomyState,
			&i.BeforePublication,
			&i.AfterPublication,
			&i.BeforeRights,
			&i.AfterRights,
			&i.BeforeDistribution,
			&i.AfterDistribution,
			&i.BeforeTrust,
			&i.AfterTrust,
			&i.Reason,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const governanceDistribution = `-- name: GovernanceDistribution :one
SELECT COALESCE((SELECT policy FROM app.resource_distribution_policies WHERE resource_id=$1),'normal')::text AS policy
`

func (q *Queries) GovernanceDistribution(ctx context.Context, resourceID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, governanceDistribution, resourceID)
	var policy string
	err := row.Scan(&policy)
	return policy, err
}

const governanceEffectiveRestrictions = `-- name: GovernanceEffectiveRestrictions :many
SELECT id,scope,reason_code,user_message,starts_at,expires_at FROM app.user_restrictions
WHERE user_id=$1 AND revoked_at IS NULL AND starts_at<=$2::timestamptz
AND (expires_at IS NULL OR expires_at>$2::timestamptz) ORDER BY scope,id
`

type GovernanceEffectiveRestrictionsParams struct {
	UserID pgtype.UUID
	Now    pgtype.Timestamptz
}

type GovernanceEffectiveRestrictionsRow struct {
	ID          pgtype.UUID
	Scope       string
	ReasonCode  string
	UserMessage string
	StartsAt    pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) GovernanceEffectiveRestrictions(ctx context.Context, arg GovernanceEffectiveRestrictionsParams) ([]GovernanceEffectiveRestrictionsRow, error) {
	rows, err := q.db.Query(ctx, governanceEffectiveRestrictions, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GovernanceEffectiveRestrictionsRow{}
	for rows.Next() {
		var i GovernanceEffectiveRestrictionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ReasonCode,
			&i.UserMessage,
			&i.StartsAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const governanceInsertAction = `-- name: GovernanceInsertAction :exec
INSERT INTO app.moderation_actions(id,actor_id,action,resource_id,source_id,user_id,restriction_id,report_id,reason,internal_note,request_id,request_fingerprint)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
`

type GovernanceInsertActionParams struct {
	ID                 pgtype.UUID
	ActorID            pgtype.UUID
	Action             string
	ResourceID         pgtype.UUID
	SourceID           pgtype.UUID
	UserID             pgtype.UUID
	RestrictionID      pgtype.UUID
	ReportID           pgtype.UUID
	Reason             string
	InternalNote       pgtype.Text
	RequestID          pgtype.UUID
	RequestFingerprint []byte
}

func (q *Queries) GovernanceInsertAction(ctx context.Context, arg GovernanceInsertActionParams) error {
	_, err := q.db.Exec(ctx, governanceInsertAction,
		arg.ID,
		arg.ActorID,
		arg.Action,
		arg.ResourceID,
		arg.SourceID,
		arg.UserID,
		arg.RestrictionID,
		arg.ReportID,
		arg.Reason,
		arg.InternalNote,
		arg.RequestID,
		arg.RequestFingerprint,
	)
	return err
}

const governanceInsertAudit = `-- name: GovernanceInsertAudit :exec
INSERT INTO app.audit_entries(id,actor_id,operation,resource_id,category_id,tag_id,user_id,source_id,contribution_id,moderation_action_id,
 fields,before_version,after_version,before_publication,after_publication,before_rights,after_rights,before_distribution,after_distribution,before_trust,after_trust,reason,before_availability,after_availability,before_taxonomy_state,after_taxonomy_state)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26)
`

type GovernanceInsertAuditParams struct {
	ID                  pgtype.UUID
	ActorID             pgtype.UUID
	Operation           string
	ResourceID          pgtype.UUID
	CategoryID          pgtype.UUID
	TagID               pgtype.UUID
	UserID              pgtype.UUID
	SourceID            pgtype.UUID
	ContributionID      pgtype.UUID
	ModerationActionID  pgtype.UUID
	Fields              []string
	BeforeVersion       pgtype.Int8
	AfterVersion        pgtype.Int8
	BeforePublication   pgtype.Text
	AfterPublication    pgtype.Text
	BeforeRights        pgtype.Text
	AfterRights         pgtype.Text
	BeforeDistribution  pgtype.Text
	AfterDistribution   pgtype.Text
	BeforeTrust         pgtype.Text
	AfterTrust          pgtype.Text
	Reason              pgtype.Text
	BeforeAvailability  pgtype.Text
	AfterAvailability   pgtype.Text
	BeforeTaxonomyState pgtype.Text
	AfterTaxonomyState  pgtype.Text
}

func (q *Queries) GovernanceInsertAudit(ctx context.Context, arg GovernanceInsertAuditParams) error {
	_, err := q.db.Exec(ctx, governanceInsertAudit,
		arg.ID,
		arg.ActorID,
		arg.Operation,
		arg.ResourceID,
		arg.CategoryID,
		arg.TagID,
		arg.UserID,
		arg.SourceID,
		arg.ContributionID,
		arg.ModerationActionID,
		arg.Fields,
		arg.BeforeVersion,
		arg.AfterVersion,
		arg.BeforePublication,
		arg.AfterPublication,
		arg.BeforeRights,
		arg.AfterRights,
		arg.BeforeDistribution,
		arg.AfterDistribution,
		arg.BeforeTrust,
		arg.AfterTrust,
		arg.Reason,
		arg.BeforeAvailability,
		arg.AfterAvailability,
		arg.BeforeTaxonomyState,
		arg.AfterTaxonomyState,
	)
	return err
}

const governanceInsertRestriction = `-- name: GovernanceInsertRestriction :exec
INSERT INTO app.user_restrictions(id,user_id,scope,reason_code,user_message,internal_note,created_by,starts_at,expires_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type GovernanceInsertRestrictionParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Scope        string
	ReasonCode   string
	UserMessage  string
	InternalNote pgtype.Text
	CreatedBy    pgtype.UUID
	StartsAt     pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) GovernanceInsertRestriction(ctx context.Context, arg GovernanceInsertRestrictionParams) error {
	_, err := q.db.Exec(ctx, governanceInsertRestriction,
		arg.ID,
		arg.UserID,
		arg.Scope,
		arg.ReasonCode,
		arg.UserMessage,
		arg.InternalNote,
		arg.CreatedBy,
		arg.StartsAt,
		arg.ExpiresAt,
	)
	return err
}

const governanceProfile = `-- name: GovernanceProfile :one
SELECT COALESCE(g.trust_level,'new')::text AS trust_level, COALESCE(g.revision,0)::bigint AS revision
FROM app.users u LEFT JOIN app.user_governance_profiles g ON g.user_id=u.id
WHERE u.id=$1 AND u.account_state='active' AND u.deleted_at IS NULL
`

type GovernanceProfileRow struct {
	TrustLevel string
	Revision   int64
}

func (q *Queries) GovernanceProfile(ctx context.Context, id pgtype.UUID) (GovernanceProfileRow, error) {
	row := q.db.QueryRow(ctx, governanceProfile, id)
	var i GovernanceProfileRow
	err := row.Scan(&i.TrustLevel, &i.Revision)
	return i, err
}

const governanceRecommendationEligible = `-- name: GovernanceRecommendationEligible :one
SELECT EXISTS(SELECT 1 FROM app.resources r JOIN app.categories c ON c.id=r.category_id
WHERE r.id=$1 AND r.publication_state='published' AND r.deleted_at IS NULL AND c.deleted_at IS NULL
AND r.content_rating='general' AND r.lifecycle='active' AND c.state='active'
AND NOT EXISTS(SELECT 1 FROM app.resource_distribution_policies p WHERE p.resource_id=r.id AND p.policy='excluded')
AND EXISTS(SELECT 1 FROM app.resource_sources s WHERE s.resource_id=r.id AND s.availability_state='active' AND s.rights_status IN ('creator_provided','confirmed'))
AND EXISTS(SELECT 1 FROM app.resource_localizations l WHERE l.resource_id=r.id AND l.locale=r.default_locale)
AND EXISTS(SELECT 1 FROM app.category_localizations l WHERE l.category_id=c.id AND l.locale=c.default_locale)
AND NOT EXISTS(SELECT 1 FROM app.resource_tags rt JOIN app.tags t ON t.id=rt.tag_id
 LEFT JOIN app.tag_localizations tl ON tl.tag_id=t.id AND tl.locale=t.default_locale
 WHERE rt.resource_id=r.id AND t.deleted_at IS NULL AND tl.tag_id IS NULL))::boolean AS eligible
`

func (q *Queries) GovernanceRecommendationEligible(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, governanceRecommendationEligible, id)
	var eligible bool
	err := row.Scan(&eligible)
	return eligible, err
}

const governanceRestrictions = `-- name: GovernanceRestrictions :many
SELECT id,user_id,scope,reason_code,user_message,starts_at,expires_at,revoked_at
FROM app.user_restrictions WHERE user_id=$1 ORDER BY starts_at DESC,id DESC
`

type GovernanceRestrictionsRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Scope       string
	ReasonCode  string
	UserMessage string
	StartsAt    pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

func (q *Queries) GovernanceRestrictions(ctx context.Context, userID pgtype.UUID) ([]GovernanceRestrictionsRow, error) {
	rows, err := q.db.Query(ctx, governanceRestrictions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GovernanceRestrictionsRow{}
	for rows.Next() {
		var i GovernanceRestrictionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Scope,
			&i.ReasonCode,
			&i.UserMessage,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const governanceRevokeRestriction = `-- name: GovernanceRevokeRestriction :execrows
UPDATE app.user_restrictions SET revoked_at=$3,revoked_by=$4,revoke_reason=$5
WHERE id=$1 AND user_id=$2 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>$3)
`

type GovernanceRevokeRestrictionParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	RevokedAt    pgtype.Timestamptz
	RevokedBy    pgtype.UUID
	RevokeReason pgtype.Text
}

func (q *Queries) GovernanceRevokeRestriction(ctx context.Context, arg GovernanceRevokeRestrictionParams) (int64, error) {
	result, err := q.db.Exec(ctx, governanceRevokeRestriction,
		arg.ID,
		arg.UserID,
		arg.RevokedAt,
		arg.RevokedBy,
		arg.RevokeReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const governanceSetDistribution = `-- name: GovernanceSetDistribution :exec
INSERT INTO app.resource_distribution_policies(resource_id,policy) VALUES($1,$2)
ON CONFLICT(resource_id) DO UPDATE SET policy=excluded.policy
`

type GovernanceSetDistributionParams struct {
	ResourceID pgtype.UUID
	Policy     string
}

func (q *Queries) GovernanceSetDistribution(ctx context.Context, arg GovernanceSetDistributionParams) error {
	_, err := q.db.Exec(ctx, governanceSetDistribution, arg.ResourceID, arg.Policy)
	return err
}

const governanceSetProfile = `-- name: GovernanceSetProfile :exec
INSERT INTO app.user_governance_profiles(user_id,trust_level,revision) VALUES($1,$2,1)
ON CONFLICT(user_id) DO UPDATE SET trust_level=excluded.trust_level,revision=app.user_governance_profiles.revision+1,updated_at=transaction_timestamp()
`

type GovernanceSetProfileParams struct {
	UserID     pgtype.UUID
	TrustLevel string
}

func (q *Queries) GovernanceSetProfile(ctx context.Context, arg GovernanceSetProfileParams) error {
	_, err := q.db.Exec(ctx, governanceSetProfile, arg.UserID, arg.TrustLevel)
	return err
}
