// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppAuthChallenge struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	AuthIdentityID pgtype.UUID
	Purpose        string
	TokenHash      string
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	ConsumedAt     pgtype.Timestamptz
	InvalidatedAt  pgtype.Timestamptz
}

type AppAuthIdentity struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Provider        string
	ProviderSubject string
	Email           pgtype.Text
	VerifiedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type AppPasswordCredential struct {
	UserID            pgtype.UUID
	PasswordHash      string
	PasswordUpdatedAt pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AppSecurityEvent struct {
	ID         int64
	UserID     pgtype.UUID
	SessionID  pgtype.UUID
	EventType  string
	OccurredAt pgtype.Timestamptz
}

type AppSession struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Kind              string
	AuthMethod        string
	TokenHash         []byte
	AuthenticatedAt   pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
}

type AppUser struct {
	ID           pgtype.UUID
	AccountState string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type AppUserProfile struct {
	UserID               pgtype.UUID
	Handle               pgtype.Text
	DisplayName          pgtype.Text
	Bio                  pgtype.Text
	SearchEngineIndexing bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type AppUserRole struct {
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}
