// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppAuditEntry struct {
	ID                  pgtype.UUID
	ActorID             pgtype.UUID
	Operation           string
	ResourceID          pgtype.UUID
	CategoryID          pgtype.UUID
	TagID               pgtype.UUID
	UserID              pgtype.UUID
	SourceID            pgtype.UUID
	ContributionID      pgtype.UUID
	ModerationActionID  pgtype.UUID
	Fields              []string
	BeforeVersion       pgtype.Int8
	AfterVersion        pgtype.Int8
	BeforeAvailability  pgtype.Text
	AfterAvailability   pgtype.Text
	BeforeTaxonomyState pgtype.Text
	AfterTaxonomyState  pgtype.Text
	BeforePublication   pgtype.Text
	AfterPublication    pgtype.Text
	BeforeRights        pgtype.Text
	AfterRights         pgtype.Text
	BeforeDistribution  pgtype.Text
	AfterDistribution   pgtype.Text
	BeforeTrust         pgtype.Text
	AfterTrust          pgtype.Text
	Reason              pgtype.Text
	OccurredAt          pgtype.Timestamptz
}

type AppAuthChallenge struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	AuthIdentityID pgtype.UUID
	Purpose        string
	TokenHash      string
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	ConsumedAt     pgtype.Timestamptz
	InvalidatedAt  pgtype.Timestamptz
}

type AppAuthIdentity struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Provider        string
	ProviderSubject string
	Email           pgtype.Text
	VerifiedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type AppCategory struct {
	ID            pgtype.UUID
	Slug          string
	DefaultLocale string
	State         string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type AppCategoryLocalization struct {
	CategoryID  pgtype.UUID
	Locale      string
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type AppContribution struct {
	ID                 pgtype.UUID
	AuthorID           pgtype.UUID
	Kind               string
	TargetResourceID   pgtype.UUID
	BaseVersion        pgtype.Int8
	Status             string
	Reason             string
	PreviousID         pgtype.UUID
	RequestID          pgtype.UUID
	RequestFingerprint []byte
	SubmittedFields    int16
	ResultResourceID   pgtype.UUID
	ResultVersion      pgtype.Int8
	CreatedAt          pgtype.Timestamptz
	DecidedAt          pgtype.Timestamptz
}

type AppContributionContent struct {
	ContributionID pgtype.UUID
	ContentKind    string
	DefaultLocale  string
	CategoryID     pgtype.UUID
	Name           string
	Summary        pgtype.Text
	Description    pgtype.Text
	Lifecycle      string
	ContentRating  string
	Slug           pgtype.Text
}

type AppContributionEvent struct {
	ContributionID pgtype.UUID
	EventType      string
	ActorID        pgtype.UUID
	Message        pgtype.Text
	InternalNote   pgtype.Text
	OccurredAt     pgtype.Timestamptz
}

type AppContributionInitialSource struct {
	ContributionID    pgtype.UUID
	ContentKind       string
	Url               string
	Label             pgtype.Text
	SourceType        string
	AvailabilityState string
}

type AppContributionLocalizationChange struct {
	ContributionID pgtype.UUID
	SnapshotKind   string
	Locale         string
	RowExists      bool
	Name           pgtype.Text
	Summary        pgtype.Text
	Description    pgtype.Text
	SuppliedFields int16
}

type AppContributionRelationChange struct {
	ContributionID      pgtype.UUID
	SnapshotKind        string
	OtherResourceID     pgtype.UUID
	RelationType        string
	Direction           string
	OtherBaseVersion    int64
	AnchorResultVersion pgtype.Int8
	OtherResultVersion  pgtype.Int8
}

type AppContributionReviewAudit struct {
	ContributionID pgtype.UUID
	ActorID        pgtype.UUID
	Action         string
	ResourceID     pgtype.UUID
	BeforeVersion  pgtype.Int8
	AfterVersion   pgtype.Int8
	OccurredAt     pgtype.Timestamptz
}

type AppContributionReviewResourceChange struct {
	ContributionID pgtype.UUID
	ResourceID     pgtype.UUID
	BeforeVersion  int64
	AfterVersion   int64
}

type AppContributionSourceChange struct {
	ContributionID    pgtype.UUID
	SnapshotKind      string
	SourceID          pgtype.UUID
	Url               pgtype.Text
	Label             pgtype.Text
	SourceType        pgtype.Text
	AvailabilityState pgtype.Text
}

type AppContributionTagChange struct {
	ContributionID pgtype.UUID
	SnapshotKind   string
	TagID          pgtype.UUID
	WasBound       bool
}

type AppModerationAction struct {
	ID                 pgtype.UUID
	ActorID            pgtype.UUID
	Action             string
	ResourceID         pgtype.UUID
	SourceID           pgtype.UUID
	UserID             pgtype.UUID
	RestrictionID      pgtype.UUID
	ReportID           pgtype.UUID
	Reason             string
	InternalNote       pgtype.Text
	RequestID          pgtype.UUID
	RequestFingerprint []byte
	OccurredAt         pgtype.Timestamptz
}

type AppPasswordCredential struct {
	UserID            pgtype.UUID
	PasswordHash      string
	PasswordUpdatedAt pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AppReport struct {
	ID                 pgtype.UUID
	ReporterID         pgtype.UUID
	ResourceID         pgtype.UUID
	SourceID           pgtype.UUID
	TargetKind         string
	Reason             string
	Body               string
	RequestID          pgtype.UUID
	RequestFingerprint []byte
	Status             string
	Version            int64
	Queue              string
	Priority           int16
	DuplicateOf        pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DecidedAt          pgtype.Timestamptz
}

type AppReportEvent struct {
	ID                 pgtype.UUID
	ReportID           pgtype.UUID
	EventType          string
	ActorID            pgtype.UUID
	RequestID          pgtype.UUID
	RequestFingerprint []byte
	SafeMessage        pgtype.Text
	InternalNote       pgtype.Text
	AuditID            pgtype.UUID
	ResolutionType     pgtype.Text
	OccurredAt         pgtype.Timestamptz
}

type AppResource struct {
	ID               pgtype.UUID
	Slug             string
	DefaultLocale    string
	CategoryID       pgtype.UUID
	PublicationState string
	Lifecycle        string
	ContentRating    string
	Version          int64
	PublishedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type AppResourceDistributionPolicy struct {
	ResourceID pgtype.UUID
	Policy     string
}

type AppResourceExternalID struct {
	ResourceID pgtype.UUID
	Namespace  string
	ExternalID string
	CreatedAt  pgtype.Timestamptz
}

type AppResourceLocalization struct {
	ResourceID  pgtype.UUID
	Locale      string
	Name        string
	Summary     pgtype.Text
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type AppResourceRelation struct {
	ID               pgtype.UUID
	SourceResourceID pgtype.UUID
	TargetResourceID pgtype.UUID
	RelationType     string
	CreatedAt        pgtype.Timestamptz
}

type AppResourceSource struct {
	ID                pgtype.UUID
	ResourceID        pgtype.UUID
	Url               string
	Label             pgtype.Text
	SourceType        string
	AvailabilityState string
	RightsStatus      string
	IsPrimary         bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AppResourceTag struct {
	ResourceID pgtype.UUID
	TagID      pgtype.UUID
}

type AppSecurityEvent struct {
	ID         int64
	UserID     pgtype.UUID
	SessionID  pgtype.UUID
	EventType  string
	OccurredAt pgtype.Timestamptz
}

type AppSession struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Kind              string
	AuthMethod        string
	TokenHash         []byte
	AuthenticatedAt   pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
}

type AppSourceCheck struct {
	ID                 pgtype.UUID
	ResourceID         pgtype.UUID
	SourceID           pgtype.UUID
	UrlFingerprint     []byte
	ResourceVersion    int64
	Outcome            string
	Note               string
	ActorID            pgtype.UUID
	RequestID          pgtype.UUID
	RequestFingerprint []byte
	ObservedAt         pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

type AppTag struct {
	ID            pgtype.UUID
	Slug          string
	DefaultLocale string
	State         string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type AppTagLocalization struct {
	TagID       pgtype.UUID
	Locale      string
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type AppUser struct {
	ID           pgtype.UUID
	AccountState string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type AppUserGovernanceProfile struct {
	UserID     pgtype.UUID
	TrustLevel string
	Revision   int64
	UpdatedAt  pgtype.Timestamptz
}

type AppUserProfile struct {
	UserID               pgtype.UUID
	Handle               pgtype.Text
	DisplayName          pgtype.Text
	Bio                  pgtype.Text
	SearchEngineIndexing bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type AppUserRestriction struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Scope        string
	ReasonCode   string
	UserMessage  string
	InternalNote pgtype.Text
	CreatedBy    pgtype.UUID
	StartsAt     pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	RevokedBy    pgtype.UUID
	RevokeReason pgtype.Text
}

type AppUserRole struct {
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}
