// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const governanceAdminRestrictions = `-- name: GovernanceAdminRestrictions :many
SELECT id, user_id, scope, reason_code, user_message, internal_note, created_by, starts_at, expires_at, revoked_at, revoked_by, revoke_reason FROM app.user_restrictions WHERE user_id=$1 ORDER BY starts_at DESC,id DESC
`

func (q *Queries) GovernanceAdminRestrictions(ctx context.Context, userID pgtype.UUID) ([]AppUserRestriction, error) {
	rows, err := q.db.Query(ctx, governanceAdminRestrictions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppUserRestriction{}
	for rows.Next() {
		var i AppUserRestriction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Scope,
			&i.ReasonCode,
			&i.UserMessage,
			&i.InternalNote,
			&i.CreatedBy,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokeReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportAdmin = `-- name: ReportAdmin :one
SELECT id, reporter_id, resource_id, source_id, target_kind, reason, body, request_id, request_fingerprint, status, version, queue, priority, duplicate_of, created_at, updated_at, decided_at FROM app.reports WHERE id=$1
`

func (q *Queries) ReportAdmin(ctx context.Context, id pgtype.UUID) (AppReport, error) {
	row := q.db.QueryRow(ctx, reportAdmin, id)
	var i AppReport
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ResourceID,
		&i.SourceID,
		&i.TargetKind,
		&i.Reason,
		&i.Body,
		&i.RequestID,
		&i.RequestFingerprint,
		&i.Status,
		&i.Version,
		&i.Queue,
		&i.Priority,
		&i.DuplicateOf,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const reportByRequest = `-- name: ReportByRequest :one
SELECT id,request_fingerprint FROM app.reports WHERE reporter_id=$1 AND request_id=$2
`

type ReportByRequestParams struct {
	ReporterID pgtype.UUID
	RequestID  pgtype.UUID
}

type ReportByRequestRow struct {
	ID                 pgtype.UUID
	RequestFingerprint []byte
}

func (q *Queries) ReportByRequest(ctx context.Context, arg ReportByRequestParams) (ReportByRequestRow, error) {
	row := q.db.QueryRow(ctx, reportByRequest, arg.ReporterID, arg.RequestID)
	var i ReportByRequestRow
	err := row.Scan(&i.ID, &i.RequestFingerprint)
	return i, err
}

const reportDecide = `-- name: ReportDecide :execrows
UPDATE app.reports SET status=$2,queue=$3,duplicate_of=$4,version=version+1,
 updated_at=transaction_timestamp(),decided_at=CASE WHEN $2::text IN ('resolved','dismissed') THEN transaction_timestamp() ELSE NULL END
WHERE id=$1 AND version=$5 AND status IN ('open','in_review')
`

type ReportDecideParams struct {
	ID              pgtype.UUID
	Status          string
	Queue           string
	DuplicateOf     pgtype.UUID
	ExpectedVersion int64
}

func (q *Queries) ReportDecide(ctx context.Context, arg ReportDecideParams) (int64, error) {
	result, err := q.db.Exec(ctx, reportDecide,
		arg.ID,
		arg.Status,
		arg.Queue,
		arg.DuplicateOf,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reportEventReplay = `-- name: ReportEventReplay :one
SELECT id,report_id,request_fingerprint FROM app.report_events WHERE actor_id=$1 AND request_id=$2
`

type ReportEventReplayParams struct {
	ActorID   pgtype.UUID
	RequestID pgtype.UUID
}

type ReportEventReplayRow struct {
	ID                 pgtype.UUID
	ReportID           pgtype.UUID
	RequestFingerprint []byte
}

func (q *Queries) ReportEventReplay(ctx context.Context, arg ReportEventReplayParams) (ReportEventReplayRow, error) {
	row := q.db.QueryRow(ctx, reportEventReplay, arg.ActorID, arg.RequestID)
	var i ReportEventReplayRow
	err := row.Scan(&i.ID, &i.ReportID, &i.RequestFingerprint)
	return i, err
}

const reportInsert = `-- name: ReportInsert :exec
INSERT INTO app.reports(id,reporter_id,resource_id,source_id,target_kind,reason,body,request_id,request_fingerprint,queue,priority)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
`

type ReportInsertParams struct {
	ID                 pgtype.UUID
	ReporterID         pgtype.UUID
	ResourceID         pgtype.UUID
	SourceID           pgtype.UUID
	TargetKind         string
	Reason             string
	Body               string
	RequestID          pgtype.UUID
	RequestFingerprint []byte
	Queue              string
	Priority           int16
}

func (q *Queries) ReportInsert(ctx context.Context, arg ReportInsertParams) error {
	_, err := q.db.Exec(ctx, reportInsert,
		arg.ID,
		arg.ReporterID,
		arg.ResourceID,
		arg.SourceID,
		arg.TargetKind,
		arg.Reason,
		arg.Body,
		arg.RequestID,
		arg.RequestFingerprint,
		arg.Queue,
		arg.Priority,
	)
	return err
}

const reportListAdmin = `-- name: ReportListAdmin :many
SELECT id, reporter_id, resource_id, source_id, target_kind, reason, body, request_id, request_fingerprint, status, version, queue, priority, duplicate_of, created_at, updated_at, decided_at FROM app.reports WHERE ($1::text IS NULL OR status=$1)
AND ($2::text IS NULL OR reason=$2)
AND ($3::text IS NULL OR queue=$3)
ORDER BY priority DESC,created_at,id LIMIT $5 OFFSET $4::bigint
`

type ReportListAdminParams struct {
	Status     pgtype.Text
	Reason     pgtype.Text
	Queue      pgtype.Text
	PageOffset int64
	FetchLimit int32
}

func (q *Queries) ReportListAdmin(ctx context.Context, arg ReportListAdminParams) ([]AppReport, error) {
	rows, err := q.db.Query(ctx, reportListAdmin,
		arg.Status,
		arg.Reason,
		arg.Queue,
		arg.PageOffset,
		arg.FetchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppReport{}
	for rows.Next() {
		var i AppReport
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ResourceID,
			&i.SourceID,
			&i.TargetKind,
			&i.Reason,
			&i.Body,
			&i.RequestID,
			&i.RequestFingerprint,
			&i.Status,
			&i.Version,
			&i.Queue,
			&i.Priority,
			&i.DuplicateOf,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportListOwned = `-- name: ReportListOwned :many
SELECT id,reporter_id,resource_id,source_id,target_kind,reason,body,status,created_at,decided_at FROM app.reports WHERE reporter_id=$1 AND ($2::text IS NULL OR status=$2)
ORDER BY created_at DESC,id DESC LIMIT $4 OFFSET $3::bigint
`

type ReportListOwnedParams struct {
	ReporterID pgtype.UUID
	Status     pgtype.Text
	PageOffset int64
	FetchLimit int32
}

type ReportListOwnedRow struct {
	ID         pgtype.UUID
	ReporterID pgtype.UUID
	ResourceID pgtype.UUID
	SourceID   pgtype.UUID
	TargetKind string
	Reason     string
	Body       string
	Status     string
	CreatedAt  pgtype.Timestamptz
	DecidedAt  pgtype.Timestamptz
}

func (q *Queries) ReportListOwned(ctx context.Context, arg ReportListOwnedParams) ([]ReportListOwnedRow, error) {
	rows, err := q.db.Query(ctx, reportListOwned,
		arg.ReporterID,
		arg.Status,
		arg.PageOffset,
		arg.FetchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportListOwnedRow{}
	for rows.Next() {
		var i ReportListOwnedRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ResourceID,
			&i.SourceID,
			&i.TargetKind,
			&i.Reason,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportLock = `-- name: ReportLock :one
SELECT id, reporter_id, resource_id, source_id, target_kind, reason, body, request_id, request_fingerprint, status, version, queue, priority, duplicate_of, created_at, updated_at, decided_at FROM app.reports WHERE id=$1 FOR UPDATE
`

func (q *Queries) ReportLock(ctx context.Context, id pgtype.UUID) (AppReport, error) {
	row := q.db.QueryRow(ctx, reportLock, id)
	var i AppReport
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ResourceID,
		&i.SourceID,
		&i.TargetKind,
		&i.Reason,
		&i.Body,
		&i.RequestID,
		&i.RequestFingerprint,
		&i.Status,
		&i.Version,
		&i.Queue,
		&i.Priority,
		&i.DuplicateOf,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const reportLockOwned = `-- name: ReportLockOwned :one
SELECT id,reporter_id,resource_id,source_id,target_kind,reason,body,status,created_at,decided_at FROM app.reports WHERE id=$1 AND reporter_id=$2 FOR UPDATE
`

type ReportLockOwnedParams struct {
	ID         pgtype.UUID
	ReporterID pgtype.UUID
}

type ReportLockOwnedRow struct {
	ID         pgtype.UUID
	ReporterID pgtype.UUID
	ResourceID pgtype.UUID
	SourceID   pgtype.UUID
	TargetKind string
	Reason     string
	Body       string
	Status     string
	CreatedAt  pgtype.Timestamptz
	DecidedAt  pgtype.Timestamptz
}

func (q *Queries) ReportLockOwned(ctx context.Context, arg ReportLockOwnedParams) (ReportLockOwnedRow, error) {
	row := q.db.QueryRow(ctx, reportLockOwned, arg.ID, arg.ReporterID)
	var i ReportLockOwnedRow
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ResourceID,
		&i.SourceID,
		&i.TargetKind,
		&i.Reason,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const reportOwned = `-- name: ReportOwned :one
SELECT id,reporter_id,resource_id,source_id,target_kind,reason,body,status,created_at,decided_at FROM app.reports WHERE id=$1 AND reporter_id=$2
`

type ReportOwnedParams struct {
	ID         pgtype.UUID
	ReporterID pgtype.UUID
}

type ReportOwnedRow struct {
	ID         pgtype.UUID
	ReporterID pgtype.UUID
	ResourceID pgtype.UUID
	SourceID   pgtype.UUID
	TargetKind string
	Reason     string
	Body       string
	Status     string
	CreatedAt  pgtype.Timestamptz
	DecidedAt  pgtype.Timestamptz
}

func (q *Queries) ReportOwned(ctx context.Context, arg ReportOwnedParams) (ReportOwnedRow, error) {
	row := q.db.QueryRow(ctx, reportOwned, arg.ID, arg.ReporterID)
	var i ReportOwnedRow
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ResourceID,
		&i.SourceID,
		&i.TargetKind,
		&i.Reason,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const reportPublicEventInsert = `-- name: ReportPublicEventInsert :exec
INSERT INTO app.report_events(id,report_id,event_type,actor_id,request_id,request_fingerprint,safe_message) VALUES($1,$2,$3,$4,$5,$6,$7)
`

type ReportPublicEventInsertParams struct {
	ID                 pgtype.UUID
	ReportID           pgtype.UUID
	EventType          string
	ActorID            pgtype.UUID
	RequestID          pgtype.UUID
	RequestFingerprint []byte
	SafeMessage        pgtype.Text
}

func (q *Queries) ReportPublicEventInsert(ctx context.Context, arg ReportPublicEventInsertParams) error {
	_, err := q.db.Exec(ctx, reportPublicEventInsert,
		arg.ID,
		arg.ReportID,
		arg.EventType,
		arg.ActorID,
		arg.RequestID,
		arg.RequestFingerprint,
		arg.SafeMessage,
	)
	return err
}

const reportPublicEvents = `-- name: ReportPublicEvents :many
SELECT event_type,safe_message,occurred_at FROM app.report_events WHERE report_id=$1 AND event_type<>'noted' ORDER BY occurred_at,id
`

type ReportPublicEventsRow struct {
	EventType   string
	SafeMessage pgtype.Text
	OccurredAt  pgtype.Timestamptz
}

func (q *Queries) ReportPublicEvents(ctx context.Context, reportID pgtype.UUID) ([]ReportPublicEventsRow, error) {
	rows, err := q.db.Query(ctx, reportPublicEvents, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportPublicEventsRow{}
	for rows.Next() {
		var i ReportPublicEventsRow
		if err := rows.Scan(&i.EventType, &i.SafeMessage, &i.OccurredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportPublicTarget = `-- name: ReportPublicTarget :one
SELECT r.id,r.slug,l.name,s.id AS source_id,
 (l.resource_id IS NOT NULL AND cl.category_id IS NOT NULL AND NOT EXISTS (
 SELECT 1 FROM app.resource_tags rt JOIN app.tags t ON t.id=rt.tag_id
 LEFT JOIN app.tag_localizations tl ON tl.tag_id=t.id AND tl.locale=t.default_locale
 WHERE rt.resource_id=r.id AND t.deleted_at IS NULL AND tl.tag_id IS NULL
 ))::boolean AS canonical_ok
FROM app.resources r JOIN app.categories c ON c.id=r.category_id
LEFT JOIN app.resource_localizations l ON l.resource_id=r.id AND l.locale=r.default_locale
LEFT JOIN app.category_localizations cl ON cl.category_id=c.id AND cl.locale=c.default_locale
LEFT JOIN app.resource_sources s ON s.resource_id=r.id AND s.id=$1::uuid
 AND s.availability_state<>'removed' AND s.rights_status IN ('unknown','creator_provided','confirmed')
WHERE r.id=$2::uuid AND r.publication_state='published' AND r.deleted_at IS NULL AND c.deleted_at IS NULL
AND ($1::uuid IS NULL OR s.id IS NOT NULL)
`

type ReportPublicTargetParams struct {
	SourceID   pgtype.UUID
	ResourceID pgtype.UUID
}

type ReportPublicTargetRow struct {
	ID          pgtype.UUID
	Slug        string
	Name        pgtype.Text
	SourceID    pgtype.UUID
	CanonicalOk bool
}

func (q *Queries) ReportPublicTarget(ctx context.Context, arg ReportPublicTargetParams) (ReportPublicTargetRow, error) {
	row := q.db.QueryRow(ctx, reportPublicTarget, arg.SourceID, arg.ResourceID)
	var i ReportPublicTargetRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.SourceID,
		&i.CanonicalOk,
	)
	return i, err
}

const reportQuota = `-- name: ReportQuota :one
SELECT count(*) FILTER(WHERE created_at>$2::timestamptz-interval '24 hours')::bigint AS recent,
 count(*) FILTER(WHERE status IN ('open','in_review'))::bigint AS pending,
 (min(created_at) FILTER(WHERE created_at>$2::timestamptz-interval '24 hours'))::timestamptz AS first_at,
 max(created_at)::timestamptz AS last_at FROM app.reports WHERE reporter_id=$1
`

type ReportQuotaParams struct {
	ReporterID pgtype.UUID
	Now        pgtype.Timestamptz
}

type ReportQuotaRow struct {
	Recent  int64
	Pending int64
	FirstAt pgtype.Timestamptz
	LastAt  pgtype.Timestamptz
}

func (q *Queries) ReportQuota(ctx context.Context, arg ReportQuotaParams) (ReportQuotaRow, error) {
	row := q.db.QueryRow(ctx, reportQuota, arg.ReporterID, arg.Now)
	var i ReportQuotaRow
	err := row.Scan(
		&i.Recent,
		&i.Pending,
		&i.FirstAt,
		&i.LastAt,
	)
	return i, err
}

const reportStaffEventInsert = `-- name: ReportStaffEventInsert :exec
INSERT INTO app.report_events(id,report_id,event_type,actor_id,request_id,request_fingerprint,safe_message,internal_note,audit_id,resolution_type) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type ReportStaffEventInsertParams struct {
	ID                 pgtype.UUID
	ReportID           pgtype.UUID
	EventType          string
	ActorID            pgtype.UUID
	RequestID          pgtype.UUID
	RequestFingerprint []byte
	SafeMessage        pgtype.Text
	InternalNote       pgtype.Text
	AuditID            pgtype.UUID
	ResolutionType     pgtype.Text
}

func (q *Queries) ReportStaffEventInsert(ctx context.Context, arg ReportStaffEventInsertParams) error {
	_, err := q.db.Exec(ctx, reportStaffEventInsert,
		arg.ID,
		arg.ReportID,
		arg.EventType,
		arg.ActorID,
		arg.RequestID,
		arg.RequestFingerprint,
		arg.SafeMessage,
		arg.InternalNote,
		arg.AuditID,
		arg.ResolutionType,
	)
	return err
}

const reportStaffEvents = `-- name: ReportStaffEvents :many
SELECT id, report_id, event_type, actor_id, request_id, request_fingerprint, safe_message, internal_note, audit_id, resolution_type, occurred_at FROM app.report_events WHERE report_id=$1 ORDER BY occurred_at,id
`

func (q *Queries) ReportStaffEvents(ctx context.Context, reportID pgtype.UUID) ([]AppReportEvent, error) {
	rows, err := q.db.Query(ctx, reportStaffEvents, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppReportEvent{}
	for rows.Next() {
		var i AppReportEvent
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.EventType,
			&i.ActorID,
			&i.RequestID,
			&i.RequestFingerprint,
			&i.SafeMessage,
			&i.InternalNote,
			&i.AuditID,
			&i.ResolutionType,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportWithdraw = `-- name: ReportWithdraw :exec
UPDATE app.reports SET status='withdrawn',version=version+1,decided_at=transaction_timestamp(),updated_at=transaction_timestamp()
WHERE id=$1 AND reporter_id=$2 AND status IN ('open','in_review')
`

type ReportWithdrawParams struct {
	ID         pgtype.UUID
	ReporterID pgtype.UUID
}

func (q *Queries) ReportWithdraw(ctx context.Context, arg ReportWithdrawParams) error {
	_, err := q.db.Exec(ctx, reportWithdraw, arg.ID, arg.ReporterID)
	return err
}

const sourceCheckByRequest = `-- name: SourceCheckByRequest :one
SELECT id, resource_id, source_id, url_fingerprint, resource_version, outcome, note, actor_id, request_id, request_fingerprint, observed_at, created_at FROM app.source_checks WHERE actor_id=$1 AND request_id=$2
`

type SourceCheckByRequestParams struct {
	ActorID   pgtype.UUID
	RequestID pgtype.UUID
}

func (q *Queries) SourceCheckByRequest(ctx context.Context, arg SourceCheckByRequestParams) (AppSourceCheck, error) {
	row := q.db.QueryRow(ctx, sourceCheckByRequest, arg.ActorID, arg.RequestID)
	var i AppSourceCheck
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.SourceID,
		&i.UrlFingerprint,
		&i.ResourceVersion,
		&i.Outcome,
		&i.Note,
		&i.ActorID,
		&i.RequestID,
		&i.RequestFingerprint,
		&i.ObservedAt,
		&i.CreatedAt,
	)
	return i, err
}

const sourceCheckInsert = `-- name: SourceCheckInsert :exec
INSERT INTO app.source_checks(id,resource_id,source_id,url_fingerprint,resource_version,outcome,note,actor_id,request_id,request_fingerprint,observed_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
`

type SourceCheckInsertParams struct {
	ID                 pgtype.UUID
	ResourceID         pgtype.UUID
	SourceID           pgtype.UUID
	UrlFingerprint     []byte
	ResourceVersion    int64
	Outcome            string
	Note               string
	ActorID            pgtype.UUID
	RequestID          pgtype.UUID
	RequestFingerprint []byte
	ObservedAt         pgtype.Timestamptz
}

func (q *Queries) SourceCheckInsert(ctx context.Context, arg SourceCheckInsertParams) error {
	_, err := q.db.Exec(ctx, sourceCheckInsert,
		arg.ID,
		arg.ResourceID,
		arg.SourceID,
		arg.UrlFingerprint,
		arg.ResourceVersion,
		arg.Outcome,
		arg.Note,
		arg.ActorID,
		arg.RequestID,
		arg.RequestFingerprint,
		arg.ObservedAt,
	)
	return err
}

const sourceCheckLatest = `-- name: SourceCheckLatest :one
SELECT id, resource_id, source_id, url_fingerprint, resource_version, outcome, note, actor_id, request_id, request_fingerprint, observed_at, created_at FROM app.source_checks WHERE source_id=$1 ORDER BY observed_at DESC,id DESC LIMIT 1
`

func (q *Queries) SourceCheckLatest(ctx context.Context, sourceID pgtype.UUID) (AppSourceCheck, error) {
	row := q.db.QueryRow(ctx, sourceCheckLatest, sourceID)
	var i AppSourceCheck
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.SourceID,
		&i.UrlFingerprint,
		&i.ResourceVersion,
		&i.Outcome,
		&i.Note,
		&i.ActorID,
		&i.RequestID,
		&i.RequestFingerprint,
		&i.ObservedAt,
		&i.CreatedAt,
	)
	return i, err
}

const sourceHealthList = `-- name: SourceHealthList :many
SELECT s.id AS source_id,r.id AS resource_id,r.version AS resource_version,r.slug AS resource_slug,s.url,s.availability_state,s.rights_status,
 EXISTS(SELECT 1 FROM app.reports p WHERE p.source_id=s.id AND p.reason='broken_link' AND p.status IN ('open','in_review'))::boolean AS open_broken_report
FROM app.resource_sources s JOIN app.resources r ON r.id=s.resource_id
WHERE r.deleted_at IS NULL AND ($1::uuid IS NULL OR s.id=$1) AND ($2::uuid IS NULL OR r.id=$2)
AND ($3::text IS NULL OR s.availability_state=$3)
AND ($4::boolean IS NULL OR $4::boolean = EXISTS(SELECT 1 FROM app.reports p WHERE p.source_id=s.id AND p.reason='broken_link' AND p.status IN ('open','in_review')))
ORDER BY (SELECT max(sc.observed_at) FROM app.source_checks sc WHERE sc.source_id=s.id) ASC NULLS FIRST,s.id
LIMIT $6 OFFSET $5::bigint
`

type SourceHealthListParams struct {
	SourceID          pgtype.UUID
	ResourceID        pgtype.UUID
	AvailabilityState pgtype.Text
	OpenBrokenReport  pgtype.Bool
	PageOffset        int64
	FetchLimit        int32
}

type SourceHealthListRow struct {
	SourceID          pgtype.UUID
	ResourceID        pgtype.UUID
	ResourceVersion   int64
	ResourceSlug      string
	Url               string
	AvailabilityState string
	RightsStatus      string
	OpenBrokenReport  bool
}

func (q *Queries) SourceHealthList(ctx context.Context, arg SourceHealthListParams) ([]SourceHealthListRow, error) {
	rows, err := q.db.Query(ctx, sourceHealthList,
		arg.SourceID,
		arg.ResourceID,
		arg.AvailabilityState,
		arg.OpenBrokenReport,
		arg.PageOffset,
		arg.FetchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SourceHealthListRow{}
	for rows.Next() {
		var i SourceHealthListRow
		if err := rows.Scan(
			&i.SourceID,
			&i.ResourceID,
			&i.ResourceVersion,
			&i.ResourceSlug,
			&i.Url,
			&i.AvailabilityState,
			&i.RightsStatus,
			&i.OpenBrokenReport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
