// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public_resource.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPublicResourceBySlug = `-- name: GetPublicResourceBySlug :one
SELECT r.id, r.slug, r.default_locale,
       COALESCE(w.name, d.name, '')::text AS name,
       COALESCE(w.summary, d.summary, '')::text AS summary,
       COALESCE(w.description, d.description, '')::text AS description,
       c.id AS category_id, c.slug AS category_slug,
       COALESCE(cw.name, cd.name, '')::text AS category_name,
       r.lifecycle, r.content_rating, r.published_at, r.updated_at,
       COALESCE((d.resource_id IS NOT NULL AND cd.category_id IS NOT NULL), false)::boolean AS canonical_ok
FROM app.resources r
JOIN app.categories c ON c.id = r.category_id AND c.deleted_at IS NULL
LEFT JOIN app.resource_localizations d ON d.resource_id = r.id AND d.locale = r.default_locale
LEFT JOIN app.resource_localizations w ON w.resource_id = r.id AND w.locale = $1::text
LEFT JOIN app.category_localizations cd ON cd.category_id = c.id AND cd.locale = c.default_locale
LEFT JOIN app.category_localizations cw ON cw.category_id = c.id AND cw.locale = $1::text
WHERE r.slug = $2 AND r.deleted_at IS NULL AND r.publication_state = 'published'
`

type GetPublicResourceBySlugParams struct {
	Locale string
	Slug   string
}

type GetPublicResourceBySlugRow struct {
	ID            pgtype.UUID
	Slug          string
	DefaultLocale string
	Name          string
	Summary       string
	Description   string
	CategoryID    pgtype.UUID
	CategorySlug  string
	CategoryName  string
	Lifecycle     string
	ContentRating string
	PublishedAt   pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	CanonicalOk   bool
}

func (q *Queries) GetPublicResourceBySlug(ctx context.Context, arg GetPublicResourceBySlugParams) (GetPublicResourceBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublicResourceBySlug, arg.Locale, arg.Slug)
	var i GetPublicResourceBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DefaultLocale,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.CategoryID,
		&i.CategorySlug,
		&i.CategoryName,
		&i.Lifecycle,
		&i.ContentRating,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.CanonicalOk,
	)
	return i, err
}

const listPublicCategories = `-- name: ListPublicCategories :many
SELECT c.id, c.slug, COALESCE(w.name, d.name, '')::text AS name,
       COALESCE(w.description, d.description, '')::text AS description,
       COALESCE((d.category_id IS NOT NULL), false)::boolean AS canonical_ok
FROM app.categories c
LEFT JOIN app.category_localizations d ON d.category_id = c.id AND d.locale = c.default_locale
LEFT JOIN app.category_localizations w ON w.category_id = c.id AND w.locale = $1::text
WHERE c.state = 'active' AND c.deleted_at IS NULL ORDER BY c.slug
`

type ListPublicCategoriesRow struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	Description string
	CanonicalOk bool
}

func (q *Queries) ListPublicCategories(ctx context.Context, locale string) ([]ListPublicCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listPublicCategories, locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicCategoriesRow{}
	for rows.Next() {
		var i ListPublicCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CanonicalOk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicResourceExternalIDs = `-- name: ListPublicResourceExternalIDs :many
SELECT namespace, external_id FROM app.resource_external_ids
WHERE resource_id = $1 ORDER BY namespace, external_id
`

type ListPublicResourceExternalIDsRow struct {
	Namespace  string
	ExternalID string
}

func (q *Queries) ListPublicResourceExternalIDs(ctx context.Context, resourceID pgtype.UUID) ([]ListPublicResourceExternalIDsRow, error) {
	rows, err := q.db.Query(ctx, listPublicResourceExternalIDs, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicResourceExternalIDsRow{}
	for rows.Next() {
		var i ListPublicResourceExternalIDsRow
		if err := rows.Scan(&i.Namespace, &i.ExternalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicResourceLocales = `-- name: ListPublicResourceLocales :many
SELECT locale FROM app.resource_localizations WHERE resource_id = $1 ORDER BY locale
`

// Child reads run in the same read-only snapshot as the public parent lookup.
func (q *Queries) ListPublicResourceLocales(ctx context.Context, resourceID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPublicResourceLocales, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var locale string
		if err := rows.Scan(&locale); err != nil {
			return nil, err
		}
		items = append(items, locale)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicResourceRelations = `-- name: ListPublicResourceRelations :many
WITH edges AS (
    SELECT outgoing.target_resource_id AS other_id, outgoing.relation_type,
           CASE WHEN outgoing.relation_type = 'related_to' THEN 'symmetric' ELSE 'outgoing' END::text AS direction
    FROM app.resource_relations outgoing WHERE outgoing.source_resource_id = $2
    UNION ALL
    SELECT incoming.source_resource_id AS other_id, incoming.relation_type,
           CASE WHEN incoming.relation_type = 'related_to' THEN 'symmetric' ELSE 'incoming' END::text AS direction
    FROM app.resource_relations incoming WHERE incoming.target_resource_id = $2
)
SELECT e.relation_type, e.direction, r.id, r.slug,
       COALESCE(w.name, d.name, '')::text AS name,
       COALESCE((d.resource_id IS NOT NULL AND cd.category_id IS NOT NULL), false)::boolean AS canonical_ok
FROM edges e
JOIN app.resources r ON r.id = e.other_id AND r.deleted_at IS NULL AND r.publication_state = 'published'
JOIN app.categories c ON c.id = r.category_id AND c.deleted_at IS NULL
LEFT JOIN app.resource_localizations d ON d.resource_id = r.id AND d.locale = r.default_locale
LEFT JOIN app.resource_localizations w ON w.resource_id = r.id AND w.locale = $1::text
LEFT JOIN app.category_localizations cd ON cd.category_id = c.id AND cd.locale = c.default_locale
ORDER BY e.relation_type, e.direction, r.slug
`

type ListPublicResourceRelationsParams struct {
	Locale     string
	ResourceID pgtype.UUID
}

type ListPublicResourceRelationsRow struct {
	RelationType string
	Direction    string
	ID           pgtype.UUID
	Slug         string
	Name         string
	CanonicalOk  bool
}

func (q *Queries) ListPublicResourceRelations(ctx context.Context, arg ListPublicResourceRelationsParams) ([]ListPublicResourceRelationsRow, error) {
	rows, err := q.db.Query(ctx, listPublicResourceRelations, arg.Locale, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicResourceRelationsRow{}
	for rows.Next() {
		var i ListPublicResourceRelationsRow
		if err := rows.Scan(
			&i.RelationType,
			&i.Direction,
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CanonicalOk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicResourceSources = `-- name: ListPublicResourceSources :many
SELECT id, url, label, source_type, availability_state, is_primary
FROM app.resource_sources
WHERE resource_id = $1
  AND availability_state IN ('active', 'unavailable', 'broken', 'restricted')
  AND rights_status IN ('unknown', 'creator_provided', 'confirmed')
ORDER BY is_primary DESC, source_type, url, id
`

type ListPublicResourceSourcesRow struct {
	ID                pgtype.UUID
	Url               string
	Label             pgtype.Text
	SourceType        string
	AvailabilityState string
	IsPrimary         bool
}

func (q *Queries) ListPublicResourceSources(ctx context.Context, resourceID pgtype.UUID) ([]ListPublicResourceSourcesRow, error) {
	rows, err := q.db.Query(ctx, listPublicResourceSources, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicResourceSourcesRow{}
	for rows.Next() {
		var i ListPublicResourceSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Label,
			&i.SourceType,
			&i.AvailabilityState,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicResourceTags = `-- name: ListPublicResourceTags :many
SELECT t.id, t.slug, COALESCE(w.name, d.name, '')::text AS name,
       COALESCE((d.tag_id IS NOT NULL), false)::boolean AS canonical_ok
FROM app.resource_tags rt
JOIN app.tags t ON t.id = rt.tag_id AND t.deleted_at IS NULL
LEFT JOIN app.tag_localizations d ON d.tag_id = t.id AND d.locale = t.default_locale
LEFT JOIN app.tag_localizations w ON w.tag_id = t.id AND w.locale = $1::text
WHERE rt.resource_id = $2
ORDER BY t.slug
`

type ListPublicResourceTagsParams struct {
	Locale     string
	ResourceID pgtype.UUID
}

type ListPublicResourceTagsRow struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	CanonicalOk bool
}

func (q *Queries) ListPublicResourceTags(ctx context.Context, arg ListPublicResourceTagsParams) ([]ListPublicResourceTagsRow, error) {
	rows, err := q.db.Query(ctx, listPublicResourceTags, arg.Locale, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicResourceTagsRow{}
	for rows.Next() {
		var i ListPublicResourceTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CanonicalOk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicResources = `-- name: ListPublicResources :many
SELECT r.id, r.slug, COALESCE(w.name, d.name, '')::text AS name,
       COALESCE(w.summary, d.summary, '')::text AS summary,
       c.id AS category_id, c.slug AS category_slug,
       COALESCE(cw.name, cd.name, '')::text AS category_name,
       r.lifecycle, r.content_rating, r.published_at, r.updated_at,
       COALESCE((d.resource_id IS NOT NULL AND cd.category_id IS NOT NULL), false)::boolean AS canonical_ok
FROM app.resources r
JOIN app.categories c ON c.id = r.category_id AND c.deleted_at IS NULL
LEFT JOIN app.resource_localizations d ON d.resource_id = r.id AND d.locale = r.default_locale
LEFT JOIN app.resource_localizations w ON w.resource_id = r.id AND w.locale = $1::text
LEFT JOIN app.category_localizations cd ON cd.category_id = c.id AND cd.locale = c.default_locale
LEFT JOIN app.category_localizations cw ON cw.category_id = c.id AND cw.locale = $1::text
WHERE r.deleted_at IS NULL AND r.publication_state = 'published'
ORDER BY r.published_at DESC, r.id DESC
LIMIT $3::bigint OFFSET $2::bigint
`

type ListPublicResourcesParams struct {
	Locale     string
	PageOffset int64
	FetchLimit int64
}

type ListPublicResourcesRow struct {
	ID            pgtype.UUID
	Slug          string
	Name          string
	Summary       string
	CategoryID    pgtype.UUID
	CategorySlug  string
	CategoryName  string
	Lifecycle     string
	ContentRating string
	PublishedAt   pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	CanonicalOk   bool
}

// Canonical localizations are LEFT JOINed deliberately. Missing canonical rows
// must reach the adapter as an invariant failure, never disappear as a 404.
// Empty optional text is forbidden by migration 6. A final empty sentinel makes
// sqlc's COALESCE result non-null; the adapter restores an explicit JSON null.
func (q *Queries) ListPublicResources(ctx context.Context, arg ListPublicResourcesParams) ([]ListPublicResourcesRow, error) {
	rows, err := q.db.Query(ctx, listPublicResources, arg.Locale, arg.PageOffset, arg.FetchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicResourcesRow{}
	for rows.Next() {
		var i ListPublicResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Summary,
			&i.CategoryID,
			&i.CategorySlug,
			&i.CategoryName,
			&i.Lifecycle,
			&i.ContentRating,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.CanonicalOk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicTags = `-- name: ListPublicTags :many
SELECT t.id, t.slug, COALESCE(w.name, d.name, '')::text AS name,
       COALESCE(w.description, d.description, '')::text AS description,
       COALESCE((d.tag_id IS NOT NULL), false)::boolean AS canonical_ok
FROM app.tags t
LEFT JOIN app.tag_localizations d ON d.tag_id = t.id AND d.locale = t.default_locale
LEFT JOIN app.tag_localizations w ON w.tag_id = t.id AND w.locale = $1::text
WHERE t.state = 'active' AND t.deleted_at IS NULL ORDER BY t.slug
`

type ListPublicTagsRow struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	Description string
	CanonicalOk bool
}

func (q *Queries) ListPublicTags(ctx context.Context, locale string) ([]ListPublicTagsRow, error) {
	rows, err := q.db.Query(ctx, listPublicTags, locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicTagsRow{}
	for rows.Next() {
		var i ListPublicTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CanonicalOk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
