// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const compareAndBumpResourceVersion = `-- name: CompareAndBumpResourceVersion :one
UPDATE app.resources SET version = version + 1, updated_at = $1
WHERE id = $2 AND version = $3 AND deleted_at IS NULL
RETURNING version
`

type CompareAndBumpResourceVersionParams struct {
	Now             pgtype.Timestamptz
	ID              pgtype.UUID
	ExpectedVersion int64
}

func (q *Queries) CompareAndBumpResourceVersion(ctx context.Context, arg CompareAndBumpResourceVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, compareAndBumpResourceVersion, arg.Now, arg.ID, arg.ExpectedVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const findResourceRelation = `-- name: FindResourceRelation :one
SELECT id FROM app.resource_relations
WHERE source_resource_id = $1 AND target_resource_id = $2 AND relation_type = $3
`

type FindResourceRelationParams struct {
	SourceResourceID pgtype.UUID
	TargetResourceID pgtype.UUID
	RelationType     string
}

func (q *Queries) FindResourceRelation(ctx context.Context, arg FindResourceRelationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findResourceRelation, arg.SourceResourceID, arg.TargetResourceID, arg.RelationType)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getResourceRevision = `-- name: GetResourceRevision :one
SELECT id, version, published_at FROM app.resources WHERE id = $1 AND deleted_at IS NULL
`

type GetResourceRevisionRow struct {
	ID          pgtype.UUID
	Version     int64
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) GetResourceRevision(ctx context.Context, id pgtype.UUID) (GetResourceRevisionRow, error) {
	row := q.db.QueryRow(ctx, getResourceRevision, id)
	var i GetResourceRevisionRow
	err := row.Scan(&i.ID, &i.Version, &i.PublishedAt)
	return i, err
}

const lockResourceCore = `-- name: LockResourceCore :one
SELECT id, slug, category_id, default_locale, publication_state, lifecycle,
       content_rating, version, published_at, created_at, updated_at
FROM app.resources WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

type LockResourceCoreRow struct {
	ID               pgtype.UUID
	Slug             string
	CategoryID       pgtype.UUID
	DefaultLocale    string
	PublicationState string
	Lifecycle        string
	ContentRating    string
	Version          int64
	PublishedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) LockResourceCore(ctx context.Context, id pgtype.UUID) (LockResourceCoreRow, error) {
	row := q.db.QueryRow(ctx, lockResourceCore, id)
	var i LockResourceCoreRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.CategoryID,
		&i.DefaultLocale,
		&i.PublicationState,
		&i.Lifecycle,
		&i.ContentRating,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resourceLocalizationExists = `-- name: ResourceLocalizationExists :one
SELECT EXISTS (SELECT 1 FROM app.resource_localizations WHERE resource_id = $1 AND locale = $2)
`

type ResourceLocalizationExistsParams struct {
	ResourceID pgtype.UUID
	Locale     string
}

func (q *Queries) ResourceLocalizationExists(ctx context.Context, arg ResourceLocalizationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, resourceLocalizationExists, arg.ResourceID, arg.Locale)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
