// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :execrows
INSERT INTO app.sessions (id, user_id, kind, auth_method, token_hash, authenticated_at, created_at,
                          last_seen_at, idle_expires_at, absolute_expires_at)
SELECT $1, u.id, 'public', $2, $3, $4, $5,
       $5, $6, $7
FROM app.users u
WHERE u.id = $8 AND u.account_state = 'active' AND u.deleted_at IS NULL
`

type CreateSessionParams struct {
	ID                pgtype.UUID
	AuthMethod        string
	TokenHash         []byte
	AuthenticatedAt   pgtype.Timestamptz
	Now               pgtype.Timestamptz
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	UserID            pgtype.UUID
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.AuthMethod,
		arg.TokenHash,
		arg.AuthenticatedAt,
		arg.Now,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveSessionByTokenHash = `-- name: FindActiveSessionByTokenHash :one
SELECT s.id, s.user_id, s.kind, s.auth_method, s.authenticated_at, s.last_seen_at, s.absolute_expires_at
FROM app.sessions s JOIN app.users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.kind = 'public' AND s.revoked_at IS NULL
  AND s.idle_expires_at > $2 AND s.absolute_expires_at > $2
  AND u.account_state = 'active' AND u.deleted_at IS NULL
`

type FindActiveSessionByTokenHashParams struct {
	TokenHash []byte
	Now       pgtype.Timestamptz
}

type FindActiveSessionByTokenHashRow struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Kind              string
	AuthMethod        string
	AuthenticatedAt   pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
}

func (q *Queries) FindActiveSessionByTokenHash(ctx context.Context, arg FindActiveSessionByTokenHashParams) (FindActiveSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, findActiveSessionByTokenHash, arg.TokenHash, arg.Now)
	var i FindActiveSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.AuthMethod,
		&i.AuthenticatedAt,
		&i.LastSeenAt,
		&i.AbsoluteExpiresAt,
	)
	return i, err
}

const getActivePublicSessionByID = `-- name: GetActivePublicSessionByID :one
SELECT s.id, s.auth_method, s.authenticated_at FROM app.sessions s JOIN app.users u ON u.id = s.user_id
WHERE s.id = $1 AND s.user_id = $2 AND s.kind = 'public'
  AND s.revoked_at IS NULL AND s.idle_expires_at > $3 AND s.absolute_expires_at > $3
  AND u.account_state = 'active' AND u.deleted_at IS NULL
`

type GetActivePublicSessionByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Now    pgtype.Timestamptz
}

type GetActivePublicSessionByIDRow struct {
	ID              pgtype.UUID
	AuthMethod      string
	AuthenticatedAt pgtype.Timestamptz
}

func (q *Queries) GetActivePublicSessionByID(ctx context.Context, arg GetActivePublicSessionByIDParams) (GetActivePublicSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getActivePublicSessionByID, arg.ID, arg.UserID, arg.Now)
	var i GetActivePublicSessionByIDRow
	err := row.Scan(&i.ID, &i.AuthMethod, &i.AuthenticatedAt)
	return i, err
}

const listActivePublicSessions = `-- name: ListActivePublicSessions :many
SELECT id, auth_method, authenticated_at, created_at, last_seen_at, idle_expires_at, absolute_expires_at
FROM app.sessions WHERE user_id = $1 AND kind = 'public' AND revoked_at IS NULL
  AND idle_expires_at > $2 AND absolute_expires_at > $2
ORDER BY created_at DESC, id DESC
`

type ListActivePublicSessionsParams struct {
	UserID pgtype.UUID
	Now    pgtype.Timestamptz
}

type ListActivePublicSessionsRow struct {
	ID                pgtype.UUID
	AuthMethod        string
	AuthenticatedAt   pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
}

func (q *Queries) ListActivePublicSessions(ctx context.Context, arg ListActivePublicSessionsParams) ([]ListActivePublicSessionsRow, error) {
	rows, err := q.db.Query(ctx, listActivePublicSessions, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePublicSessionsRow{}
	for rows.Next() {
		var i ListActivePublicSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthMethod,
			&i.AuthenticatedAt,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.IdleExpiresAt,
			&i.AbsoluteExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE app.sessions SET revoked_at = $1
WHERE user_id = $2 AND revoked_at IS NULL
`

type RevokeAllUserSessionsParams struct {
	Now    pgtype.Timestamptz
	UserID pgtype.UUID
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, arg.Now, arg.UserID)
	return err
}

const revokeOtherPublicSessions = `-- name: RevokeOtherPublicSessions :exec
UPDATE app.sessions SET revoked_at = $1
WHERE user_id = $2 AND id <> $3 AND kind = 'public' AND revoked_at IS NULL
`

type RevokeOtherPublicSessionsParams struct {
	Now       pgtype.Timestamptz
	UserID    pgtype.UUID
	CurrentID pgtype.UUID
}

func (q *Queries) RevokeOtherPublicSessions(ctx context.Context, arg RevokeOtherPublicSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherPublicSessions, arg.Now, arg.UserID, arg.CurrentID)
	return err
}

const revokePublicSessionByID = `-- name: RevokePublicSessionByID :execrows
UPDATE app.sessions SET revoked_at = $1
WHERE id = $2 AND user_id = $3 AND kind = 'public' AND revoked_at IS NULL
  AND idle_expires_at > $1 AND absolute_expires_at > $1
`

type RevokePublicSessionByIDParams struct {
	Now    pgtype.Timestamptz
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RevokePublicSessionByID(ctx context.Context, arg RevokePublicSessionByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePublicSessionByID, arg.Now, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE app.sessions SET revoked_at = $1
WHERE id = $2 AND user_id = $3 AND kind = 'public' AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	Now    pgtype.Timestamptz
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.Now, arg.ID, arg.UserID)
	return err
}

const touchSession = `-- name: TouchSession :execrows
UPDATE app.sessions s SET last_seen_at = $1,
    idle_expires_at = LEAST($2::timestamptz, s.absolute_expires_at)
WHERE s.id = $3 AND s.kind = 'public' AND s.revoked_at IS NULL
  AND s.idle_expires_at > $1 AND s.absolute_expires_at > $1
  AND s.last_seen_at <= $4
  AND EXISTS (SELECT 1 FROM app.users u WHERE u.id = s.user_id AND u.account_state = 'active' AND u.deleted_at IS NULL)
`

type TouchSessionParams struct {
	Now           pgtype.Timestamptz
	IdleExpiresAt pgtype.Timestamptz
	ID            pgtype.UUID
	TouchBefore   pgtype.Timestamptz
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession,
		arg.Now,
		arg.IdleExpiresAt,
		arg.ID,
		arg.TouchBefore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
