// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: taxonomy.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const categoryLocalizationExists = `-- name: CategoryLocalizationExists :one
SELECT EXISTS (SELECT 1 FROM app.category_localizations WHERE category_id = $1 AND locale = $2)
`

type CategoryLocalizationExistsParams struct {
	CategoryID pgtype.UUID
	Locale     string
}

func (q *Queries) CategoryLocalizationExists(ctx context.Context, arg CategoryLocalizationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, categoryLocalizationExists, arg.CategoryID, arg.Locale)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCategoryState = `-- name: GetCategoryState :one
SELECT id, slug, default_locale, state FROM app.categories WHERE id = $1 AND deleted_at IS NULL
`

type GetCategoryStateRow struct {
	ID            pgtype.UUID
	Slug          string
	DefaultLocale string
	State         string
}

func (q *Queries) GetCategoryState(ctx context.Context, id pgtype.UUID) (GetCategoryStateRow, error) {
	row := q.db.QueryRow(ctx, getCategoryState, id)
	var i GetCategoryStateRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DefaultLocale,
		&i.State,
	)
	return i, err
}

const getTagState = `-- name: GetTagState :one
SELECT id, slug, default_locale, state FROM app.tags WHERE id = $1 AND deleted_at IS NULL
`

type GetTagStateRow struct {
	ID            pgtype.UUID
	Slug          string
	DefaultLocale string
	State         string
}

func (q *Queries) GetTagState(ctx context.Context, id pgtype.UUID) (GetTagStateRow, error) {
	row := q.db.QueryRow(ctx, getTagState, id)
	var i GetTagStateRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DefaultLocale,
		&i.State,
	)
	return i, err
}

const lockCategoryLocalizationParent = `-- name: LockCategoryLocalizationParent :one
SELECT id, default_locale FROM app.categories WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

type LockCategoryLocalizationParentRow struct {
	ID            pgtype.UUID
	DefaultLocale string
}

func (q *Queries) LockCategoryLocalizationParent(ctx context.Context, id pgtype.UUID) (LockCategoryLocalizationParentRow, error) {
	row := q.db.QueryRow(ctx, lockCategoryLocalizationParent, id)
	var i LockCategoryLocalizationParentRow
	err := row.Scan(&i.ID, &i.DefaultLocale)
	return i, err
}

const lockTagLocalizationParent = `-- name: LockTagLocalizationParent :one
SELECT id, default_locale FROM app.tags WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

type LockTagLocalizationParentRow struct {
	ID            pgtype.UUID
	DefaultLocale string
}

func (q *Queries) LockTagLocalizationParent(ctx context.Context, id pgtype.UUID) (LockTagLocalizationParentRow, error) {
	row := q.db.QueryRow(ctx, lockTagLocalizationParent, id)
	var i LockTagLocalizationParentRow
	err := row.Scan(&i.ID, &i.DefaultLocale)
	return i, err
}

const tagLocalizationExists = `-- name: TagLocalizationExists :one
SELECT EXISTS (SELECT 1 FROM app.tag_localizations WHERE tag_id = $1 AND locale = $2)
`

type TagLocalizationExistsParams struct {
	TagID  pgtype.UUID
	Locale string
}

func (q *Queries) TagLocalizationExists(ctx context.Context, arg TagLocalizationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, tagLocalizationExists, arg.TagID, arg.Locale)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
